### ISSUE TITLE
Shared element text size change

### ISSUE THREAD

**Issue by israelidanny** [fram-x/FluidTransitions#100]
Hey, sorry for the multitude of issues :)

So one more thing I'm trying to do is gradually increase the size of text as I animate from a list view & something becomes a page header.

The text position animates great, but `fontSize` doesn't seem like it can be animated.

**Comment by chrfalch** [comment]
Np, @israelidanny :-)

**Comment by chrfalch** [comment]
@israelidanny Try the above PR and see what you think :-)

**Comment by israelidanny** [comment]
@chrfalch will do some time in the next day or so :) This component is one of the best things ever to happen to navigation in React Native. I'm majorly digging it.

Can't wait to make some PR's myself later. 

Thanks for the phenomenal response times and great motivation & support.

**Comment by chrfalch** [comment]
Thanks for the inspiration, had some time on my hands this week, so you caught me in a really great moment :-)

**Comment by chrfalch** [comment]
I'm seeing some jumping in the text transition that I'm working on. Stay tuned.

**Comment by chrfalch** [comment]
Tested. Will not work using Animated from react-native. New version using reanimated in the works.
