### ISSUE TITLE
version 0.2.71 upgrade error: TypeError: in this environment the sources must be an object

### ISSUE THREAD

**Issue by rohan-jansen** [fram-x/FluidTransitions#112]
After upgrading to version 0.2.71, getting the following error. Nothing has changed apart from upgrading.

![image](https://user-images.githubusercontent.com/20238378/46214980-93355480-c33c-11e8-821a-1062dfc03cde.png)

**Comment by rohan-jansen** [comment]
This seems to be an issue with createFluidNavigator as if I switch out createFluidNavigator for createStackNavigator, code compiles again.

**Comment by rohan-jansen** [comment]
`const PaymentFlowNavigator = createFluidNavigator(
  {
    Loans: {
      screen: Loans,
    },
    PaymentTypeSelection: {
      screen: PaymentTypeSelection,
    },
    PaymentMethods: {
      screen: PaymentMethods,
      navigationOptions: {
        header: null,
      },
    },
    PaymentMethodDetail: {
      screen: PaymentMethodDetail,
      navigationOptions: {
        header: null,
      },
    },
    OnetimeStepOne: {
      screen: OnetimeStepOne,
    },
    OnetimeStepTwo: {
      screen: OnetimeStepTwo,
    },
    OnetimePaymentCompleted: {
      screen: OnetimePaymentCompleted,
    },
    OnetimePaymentFailed: {
      screen: OnetimePaymentFailed,
    },
    AutoMonthlyStepOne: {
      screen: AutoMonthlyStepOne,
    },
    AutoMonthlyStepTwo: {
      screen: AutoMonthlyStepTwo,
    },
    AutoMonthlyPaymentCompleted: {
      screen: AutoMonthlyPaymentCompleted,
    },
    AutoMonthlyPaymentFailed: {
      screen: AutoMonthlyPaymentFailed,
    },
    AutoMonthlyEdit: {
      screen: AutoMonthlyEdit,
    },
  },
  {
    mode: 'modal',
    headerMode: 'none',
    transitionConfig: {
      duration: 300,
      timing: Animated.timing,
      easing: Easing.out(Easing.quad),
      useNativeDriver: true,
    },
  },
);

export default PaymentFlowNavigator;`

**Comment by rohan-jansen** [comment]
Which then gets consumed in a createBottomTabNavigator here

`const SignedInStackNavigator = createBottomTabNavigator(
  {
    Payments: {
      screen: PaymentFlowNavigator,
    },
    PaymentsHistory: {
      screen: PaymentsHistory,
    },
    MakePayment: {
      screen: () => null,
      navigationOptions: () => ({
        tabBarIcon: <PayTab />,
      }),
    },
    ContactUs: {
      screen: ContactUs,
    },
    FAQ: {
      screen: FAQ,
    },
  },
);

export default SignedInStackNavigator;`

**Comment by chrfalch** [comment]
Hi @rohan-jansen, Would it be possible to create a small example and zip it down so that I can find out why this is happening?

**Comment by rohan-jansen** [comment]
Hi @chrfalch it's quite a complicated setup, been trying to get something simple to work but not getting far. If it helps, after the upgrade, if I replace the fluidNavigator with a stackNavigator, everything works, so the issue lies somewhere in the PaymentFlowNavigator which is the second comment I made above. Sorry that I can't give more info

**Comment by hesselberg** [comment]
Had the same issue -- downgraded to v. 0.2.6 and it works smoothly

**Comment by rohan-jansen** [comment]
On v. 0.2.6 now, works fine. But a little bit worried about some of the issues I've been experiencing, our app is currently in production, and we we have quite a large part of our stack using this fluid framework. Not being able to upgrade to newer versions is putting us into a bit of a tight spot.

**Comment by chrfalch** [comment]
Fully understand - to be able to fix this I need some kind of simple repo... Maybe @hesselberg could help? I'm not seeing this in my tests, but its probably something that should be easy to fix.

**Comment by rohan-jansen** [comment]
Oh yeah I didn't mean it in a strange way, I'm loving this framework, it's enabled us to do some incredible work :) ... Just having some issues now thats preventing us from releasing our next version, and because its so coupled to FluidTransitions, I can't just remove it for this release. If push comes to shove, do you perhaps do any contract work? We can perhaps put an NDA together and then share the repo with you to check through? Not sure if this could help

**Comment by chrfalch** [comment]
Hi @rohan-jansen - no problem ;-) We'd be happy to help you out with contracting work, signing an NDA should be fine. You can contact med at `christian at framx dot no` and we'll continue the discussion there.

**Comment by hesselberg** [comment]
Creating a small repo as we speak -- I'll dm you the details

**Comment by chrfalch** [comment]
Thanks, @hesselberg!

**Comment by rohan-jansen** [comment]
@chrfalch Perfect, will keep on doing some digging from my side, but if all else fails we'll be in contact. Thanks! @hesselberg let me know what you find ;)

**Comment by chrfalch** [comment]
Thanks, @hesselberg - found the issue ;-) Will submit a quick fix.

**Comment by hesselberg** [comment]
@chrfalch great!

**Comment by rohan-jansen** [comment]
Great stuff @hesselberg and @chrfalch please let me know once you've got this sorted :) .. Thanks for the quick turn around time!

**Comment by chrfalch** [comment]
Release 0.2.72 :-) @rohan-jansen, @hesselberg

**Comment by rohan-jansen** [comment]
Awesome :) 👍

**Comment by rohan-jansen** [comment]
Hi @chrfalch just a heads up, sent you a mail regarding the contracting work mentioned above to the email on your GitHub profile as I couldn't find contact details on your website. Let me know if this was ok.
