### ISSUE TITLE
Transition Element in ScrollView

### ISSUE THREAD

**Issue by padampadam** [fram-x/FluidTransitions#113]
Ok, so i am transitioning from my Home-Screen to my Details-Screen, which works perfectly. Also going back is working fine. Problem is, my Image in the Details-Screen is in a ScrollView. If i scroll down and navigate back, it is transitioning the element back from its initial position, instead of its current position. Any ideas?

**Comment by chrfalch** [comment]
Hi @padampadam - thanks for submitting the issue. Would it be possible for you to create a simple reproduction using https://snack.expo.io that describes the problem? I'm a little bit unsure if I completely understand why the image in the original screen has changed its position.

**Comment by padampadam** [comment]
https://snack.expo.io/@marianbeuther/fluid-transition-bug this is a quick reproduction, here is what i meant:

![bildschirmaufnahme 2018-10-09 um 09 48 14](https://user-images.githubusercontent.com/773986/46654397-0a72b000-cba9-11e8-8def-3924bd84d7e5.gif)

**Comment by padampadam** [comment]
@chrfalch did you get a chance to take a look at this?

**Comment by padampadam** [comment]
@chrfalch possible, although i am not sure.
you see, if you go from screen A -> B, and then A <- B , there is no problem. But if you Go A -> B -> C, then go back from C to B, then MOVE the Scrollview in B around and then go back from B to A, it uses the elements position BEFORE you moved it around.
Doe you recalculate the positions on goBack or are they stored somewhere? This could be the cause.

**Comment by chrfalch** [comment]
Should be fixed in #130
