### ISSUE TITLE
Have background slide out sideways?

### ISSUE THREAD

**Issue by Jonovono** [fram-x/FluidTransitions#115]
Hi. I am wondering how I could have the entire background slide out, similar to a tab navigation behaviour, but also keep other shared elements on the screen that navigate to their new places.

Is this possible? Most of the examples just slide out a certain component, not the entire background.

Any help would be great! Thanks :)

**Comment by chrfalch** [comment]
Hi @Jonovono, the purpose of this library is to add support for individual transitions, not full screen transitions.
