### ISSUE TITLE
pointerEvents="box-none" on internal views

### ISSUE THREAD

**Issue by siderakis** [fram-x/FluidTransitions#116]
I'd like to interact with a view that's absolutely positioned behind the FluidNavigator. I'm using the FluidNavigator to display overlays to the UI which I'd like to interact with. If all views have pointerEvents="box-none" touch events would reach the view behind the FluidNavigator. 

The issue is that not all views internal to FluidNavigator have pointerEvents="box-none" so it's currently not possible.

Let me know if what I'm trying to achieve or if the issue isn't clear.

Thanks!

**Comment by chrfalch** [comment]
Hi, @siderakis - thanks for submitting the issue. I'm a little bit uncertain about what you're trying to do and if it will work for existing usage of the library. Feel free to try to dive into the code and see if you can identify some places you'd like to change this - PRs are welcome!
