### ISSUE TITLE
Add typescript support

### ISSUE THREAD

**Issue by fredericocurti** [fram-x/FluidTransitions#120]
I know its not very requested but it would be awesome to see type checking on this awesome lib :)

**Comment by chrfalch** [comment]
Hi @fredericocurti, thanks for submitting an issue! I'm aware of the typing issues... A new version using react-native-reanimated is in the works, maybe we'll add some ts-magic there!

**Comment by JediMasterB8ter420** [comment]
I luv subtitles and submissive tight Fuck Holes w/ Mouth Skills to Swallow Daddys Hot Sticky Double shot of Man Nectar. I fuck all night 👅 💃

**Comment by jacek213** [comment]
could use types too!

**Comment by jaulz** [comment]
@chrfalch does it make sense to work on types or are you already working on it? Would you anyway rather prefer it to be on DefinitelyTyped or in this library itself?

**Comment by atrauzzi** [comment]
Ideally it goes in the library itself.  DefinitelyTyped is only for when the maintainers aren't sympathetic towards TS 😢

**Comment by chrfalch** [comment]
I would be really happy to get some types in here :) I'm working on the next version of the library - it is written entirely in TypeScript but for now this would really help.

**Comment by jaulz** [comment]
https://github.com/fram-x/FluidTransitions/pull/186
