### ISSUE TITLE
Some strange behavior appears in Android.

### ISSUE THREAD

**Issue by AkilLis** [fram-x/FluidTransitions#121]
It is working fine on ios devices. Tested on 5s,6s. But on android devices /Samsung s7, Samsung A8/ shared transition works not working well.  Usage is same as an example project. Transition image's ratio is different. Small image is cutted from the bottom. [example video](https://drive.google.com/open?id=1-dvPYSPdvi5-AZYh7_1Vi7zvJXob_cmb)

**Comment by AkilLis** [comment]
sorry for the bothering it was a my own fault.

**Comment by iremlopsum** [comment]
@AkilLis I have same problem. Can you share what mistake you made?

**Comment by saraf22** [comment]
what was ur fault
