### ISSUE TITLE
How can I turn off the animation of elements when switching between navigators?

### ISSUE THREAD

**Issue by MatthewPattell** [fram-x/FluidTransitions#122]
Example:

```
const RootNavigator = createStackNavigator({
    SPLASH:                          {screen: SplashScreenStore},
    REGISTRATION: {
        screen: ({navigation}) => <RegistrationNavigator screenProps={{rootNavigation: navigation}} />
    },
   USER:         {
        screen: ({navigation}) => <MainNavigator screenProps={{rootNavigation: navigation}} />
    },
}, {
    initialRouteName:  'SPLASH',
    headerMode:        'none',
    navigationOptions: {
        gesturesEnabled: false,
    },
    mode:              'card',
    cardStyle:         {
        backgroundColor: 'white',
    },
    transitionConfig,
});
```
RegistrationNavigator and MainNavigator is fluid navigator.

If i change screen from SPLASH to USER:
1. SPLASH fadeout.
2. I see white screen 
3. Elements from first screen of USER navigator appear (from top and bottom animation)

Now, i change screen to REGISTRATION. Previous steps repeats.

Then I change again screen to USER.
1. REGISTRATION screen fadeout.
2. I see elements from first screen USER navigator. They are already present on the screen and white screen not shown.

How can I turn off the animation of elements when switching between navigators?

By the way, switching between the screens of one navigator works fine (without a white screen)

**Comment by chrfalch** [comment]
Hi @MatthewPattell - thanks for the question. Have you tried putting RegistrationNavigator and MainNavigator into one Fluid Navigator?

**Comment by chrfalch** [comment]
Unfortunately not.

**Comment by MatthewPattell** [comment]
I'm understood, thank you
