### ISSUE TITLE
autoFocus not working, duplicate textinput

### ISSUE THREAD

**Issue by fendorio** [fram-x/FluidTransitions#126]
Seems this library makes the autoFocus property of RN's TextInput break, looks like two (or N) inputs get rendered, the first (lowest zIndex) gets the focus, but the text is not visible as you type, as there is another TextInput sat on top of it. 

```javascript
class App extends React.Component {

    render () {
         return ( <TextInput autoFocus={true} />)
    } 

}
```

**Comment by fendorio** [comment]
This seems to be because of the hidden overlay(underlay?) that's placed underneath each screen, that seems to load first, thus the input on the overlay gets focused. 

The behaviour here is that when the screen loads, it looks like it does autofocus, i.e. the keyboard pops up, and you can type into it, but the characters do not show, because they're being entered into the hidden input, not the *actual input. 

Hope that makes sense? Happy to elaborate and provide an example if needed, and possibly to fix it, I won't be free to do that for some weeks though, will certainly be checking back in to check this issue.

**Comment by chrfalch** [comment]
Hi @fendorio! Thanks for submitting the issue. I'm currently looking at how this can be solved. You are correct that we're creating elements for the transition, and although this is necessary to be able to get shared transitions to work correctly, it is not necessarily needed for all regular transitions.

**Comment by chrfalch** [comment]
A new version will soon be released with support for the `inline` property, making transitions run without being duplicated. This will save memory, increase performance and possibly also solve your problem :) Closing for now - reopen if the issue still exist after adding the `inline` property to your TransitionViews.
