### ISSUE TITLE
Setting navigationOptions for FluidNavigator Header not working

### ISSUE THREAD

**Issue by steve-else** [fram-x/FluidTransitions#129]
react-native: 0.57.0
react-navigation: 2.17.0
react-navigation-fluid-transitions: 0.2.72

For some reason setting the navigationOptions for the header does not seem to work. I am attempting to set it as shown in below example:

```
export const AccountStack = createFluidNavigator({
  Account: {
    screen: Account,
    navigationOptions: () => ({
      title: 'Account',
    }),
  },
});
```

It does not show the header bar as a result of this. If I use the generic `createStackNavigator` instead, it does show the header as intended. Any ideas?

**Comment by chrfalch** [comment]
Hi @steve-else, thanks for submitting an issue. FluidTransition does not support headers like the stack navigator, so it won't work. Closing this issue.

**Comment by octodhruv** [comment]
Hi @chrfalch! Great work in creating this library, it looks great! I was wondering if you had any transparency as to why this isn't supported? Is this a design / use-case decision, or a technical limitation?

Thank you!

**Comment by octodhruv** [comment]
to clarify, _this_ meaning why FluidTransition does not support headers...
