### ISSUE TITLE
Give additional props to inner of shared element to determine transitioning state

### ISSUE THREAD

**Issue by mmtootmm** [fram-x/FluidTransitions#132]
Thanks for useful library.

I'm trying to implement transitions with shared element.
In my case, contents of a photo slider that requires static width information are not resizing.
Maybe, it's in the specifications.

If inner elements receive some information about transitioning state, I can display temporary layout during animation(like displaying focused image in absoluteFill).
Is there any plan to give additional props to inner of shared element?
https://github.com/fram-x/FluidTransitions/blob/develop/lib/Utils/createAnimatedWrapper.js#L74

Sorry for cheap English.

**Comment by chrfalch** [comment]
Hui, @mmtootmm - check out the Animated Property example - this will probably give you something that you can work with.

Closing this one.
