### ISSUE TITLE
Fluid Navigator, Too much load

### ISSUE THREAD

**Issue by WrathChaos** [fram-x/FluidTransitions#134]
Hello, 
Thank you this awesome library!

I use Fluid Navigator for our app. Our app has a full cycle use cases. For example, user goes ->
MainScreen -> A-Screen -> MainScreen -> B-Screen -> C-Screen -> MainScreen 

Something like that and goes on.. After some navigations, whole app's performance goes down dramatically.. What should I do for these kinds of navigations ?? 

I navigate with this code : 
`this.props.navigation.push(path, param); `

Also my main navigator is something like : 

```
const MainNavigator = FluidNavigator(
			{
				map: MainScreen,
				aScreen: AScreen,
				bScreen: BScreen,
				cScreen: CScreen,
				example: Example
			},
			{
				navigationOptions: {
					tabBarVisible: false,
					gesturesEnabled: true
				},
				lazy: true
			}
		);
```

One last point, on my MainScreep has a MapView and it contains 100+ markers but on the first opening it is smooth AF. After I go to B-Screen and navigate to MainScreen.. It lags too much.

What should I do about this ? :) 
Thank you!

**Comment by chrfalch** [comment]
Hi @WrathChaos - I'm currently working on a fix that will improve this behavior (#126 for a quick explanation). If you're using maps in a shared transition you will unfortunately be out of luck - the map will be recreated.

**Comment by chrfalch** [comment]
The problem is the issue you're seeing with too many controls on the screen. Would  suggest not using the FluidNavigator for setups where you complex control hierarchies.

**Comment by WrathChaos** [comment]
Thank you so much :)
