### ISSUE TITLE
Cannot use scrollToEnd in ScrollView inside Transition

### ISSUE THREAD

**Issue by timomeh** [fram-x/FluidTransitions#136]
Using `scrollToEnd` on a ScrollView does not work if the ScrollView is inside a `Transition` component. When I remove the wrapping `Transition` component, it works without a problem.

The ref is there, but nothing happens.

```js
class MyScreen extends React.PureComponent {
  scrollRef = React.createRef()

  handleButtonPress = () => {
    // this get's triggered and `this.scrollRef.current` is set,
    // but the ScrollView does not scroll
    this.scrollRef.current.scrollToEnd()
  }

  render() {
    return (
      <Transition>
        <ScrollView ref={this.scrollRef}>
          // ...
          <Button onPress={this.handleButtonPress} title="Scroll Down" />
        </ScrollView>
      </Transition>
    )
  }
}
```

I noticed that the `onScroll` handler gets called, even with the correct event data, as if it were scrolling down. But it doesn't visually scroll down.

I tested this on a real Android Device and on an iOS Simulator.

Here's an expo snack: https://snack.expo.io/BylcD2WAQ

(I used FluidTransitions 0.2.6 in the expo snack because 0.2.7* doesn't work in expo snack. But the behavior is the same in 0.2.73)

**Comment by timomeh** [comment]
I just noticed that I wrote "Test it here and it will throw an error" in the expo snack. That's incorrect, it doesn't throw an error.

**Comment by chrfalch** [comment]
Thanks for the issue, @timomeh and thanks for the suggested solution @mohammad-sn. I'm about to release a new version with support for inline transitions - just set the `inline` property for a transition and it won't be duplicated onto the transition overlay. Closing this for now - should be reopened if this solution doesn't work.
