### ISSUE TITLE
Warning: Importing the stack Transitioner directly from react-navigation is now deprecated

### ISSUE THREAD

**Issue by njacob1001** [fram-x/FluidTransitions#137]
Warning: Importing the stack Transitioner directly from react-navigation is now deprecated, Instead, import { Transitioner } from "react-navigation-stack"

Stack
Transitioner

**Comment by marcelotmagalhaes** [comment]
Same problem here...

```
"react": "16.6.1",
"react-native": "0.57.5",
"react-navigation": "^3.0.0",
"react-navigation-fluid-transitions": "^0.2.73",
```

<img width="450" alt="screen shot 2018-11-26 at 8 04 38 pm" src="https://user-images.githubusercontent.com/26512527/49051618-aa66b600-f1b6-11e8-929a-1ebf188a6049.png">
