### ISSUE TITLE
Detox testing compatibility

### ISSUE THREAD

**Issue by kevinvanzyl2** [fram-x/FluidTransitions#138]
I am having issues when doing detox testing, fluid-transitions seems to create some kind of nesting structure which fails my detox tests for toBeVisible for >75%.

Here is the expect rule on Detox docs: https://github.com/wix/Detox/blob/master/docs/APIRef.Expect.md#tobevisible

Here is the full detail in StackOverflow:
https://stackoverflow.com/questions/53477506/detox-e2e-testing-with-react-navigation-and-react-native-fluid-transitions-exp

**Comment by chrfalch** [comment]
Hi @kevinvanzyl2 - FluidTransitions creates a copy of all transition elements and runs the transition in a separate overlay, this is probably why it fails.

**Comment by chrfalch** [comment]
Will close this issue due to inactivity.
