### ISSUE TITLE
Please upgrade to React Navigation 3.x

### ISSUE THREAD

**Issue by PublicParadise** [fram-x/FluidTransitions#139]
## Please upgrade to React Navigation 3.x

Current version of `react-navigation` in `package.json` is 2.16.0:
```
"react-navigation": "2.16.0"
```

The latest version of `react-navigation` is [3.0.1](https://github.com/react-navigation/react-navigation/blob/master/package.json).

Using `react-navigation` v2.16.0 makes `FluidTransitions` incompatible with many modules that require `react-navigation` v3.x .

**Comment by jrwpatterson** [comment]
+1

**Comment by gino8080** [comment]
bump! +1

**Comment by chrfalch** [comment]
Hi @PublicParadise and others :) Feel free to submit PRs for this - my time is a little bit limited at the moment. Will get back to this though.
