### ISSUE TITLE
Not compatible with IPhone XS Max and XR. 

### ISSUE THREAD

**Issue by AkilLis** [fram-x/FluidTransitions#142]
Great library. With this two devices navigation HEADER is cutted from the top. Related screenshots are attached. Im just thinking **Header height helpers** working not correct the latest iphone devices.

![simulator screen shot - iphone xs max - 2018-12-02 at 17 06 31](https://user-images.githubusercontent.com/4900613/49337860-01f0a000-f655-11e8-9955-42fc177a238b.png)

**Comment by chrfalch** [comment]
Hi @AkilLis - You should be able to use the `SafeAreaView` included in both React Native and in react-navigation to fix this. Closing this issue since I believe it is not related not the Fluid Transitions library.
