### ISSUE TITLE
Support for React Native Router Flux

### ISSUE THREAD

**Issue by anooj1483** [fram-x/FluidTransitions#149]
Please provide support for [React Native Router Flux](https://github.com/aksonov/react-native-router-flux)

**Comment by chrfalch** [comment]
Hi, @anooj1483, thanks for the feature request - no plans for this currently, but we'll keep it on the list.

**Comment by FirdousNath** [comment]
We need this damn badly :(

**Comment by shubhamkes** [comment]
Is there any plan in near future for this?
