### ISSUE TITLE
Screen is transparent on app load when using redux and redux-persist

### ISSUE THREAD

**Issue by computerjazz** [fram-x/FluidTransitions#15]
My app uses a FluidNavigator as one route within a react-navigation TabNavigator. I'm storing nav state in redux and persisting with redux-persist. The initial route the FluidNavigator renders is a list, and when an item is tapped it becomes the header in the following screen. I'll call the two screens `ListScreen` and `ItemScreen`. 

All works well initially when navigating from `ListScreen` to `ItemScreen`, however, if I then refresh the app and it rehydrates from saved nav state, I see the underlying `ListScreen` even though I was previously on `ItemScreen`. Then the header item from`ItemScreen` transitions in, and then it disappears.

Even though I appear to be back on `ListScreen`, I still have two screens on the stack and according to my nav state I'm still on `ItemScreen`. I can click buttons that are on `ItemScreen` even though I can't see them, so I believe the screen is there but at 0 opacity.

**Comment by chrfalch** [comment]
Hi @computerjazz! Thanks for the feedback. Would it be possible for you to either a simple snack (https://snack.expo.io) showing the issue so I can try to find a solution?

**Comment by computerjazz** [comment]
Hi!
Here's a snack: https://snack.expo.io/SyeOwMThG

I'm not exactly sure how redux-persist plays with Expo, but some similar behavior is present. Navigating around the first time the app is launched works as expected. But if I close the app and relaunch, it opens in the correct state, but from there on out the transitions no longer work. I also occasionally see the blank white screen that can still be tapped, but I'm not sure when that happens.

This is a really cool library! Let me know if I can help debug further.

![persistfluid](https://user-images.githubusercontent.com/6730148/39213520-aaa8a1ea-47c6-11e8-9602-8dba13d90489.gif)

**Comment by chrfalch** [comment]
Thanks so much @computerjazz for providing this example. I might know what this is all about and will test with some new features I'm working on.

**Comment by chrfalch** [comment]
Closing this one due to inactivity. @computerjazz
