### ISSUE TITLE
How to swipe forward (from right to left)

### ISSUE THREAD

**Issue by nahuelhds** [fram-x/FluidTransitions#150]
I've been able to configure horizontal gestures but it only comes with swipe back. I would like to know how to detect the swipe forward action in order to send the user to the next screen.

I know that it's impossible to know the next screen until it's pushed in the stack. I'm asking if there is some way to detect the swipe action.

Thanks in advance.

**Comment by chrfalch** [comment]
Since this is based on a StackNavigator there is basically no implicit forward route, and therefore no way to know where to swipe to. A suggestion/feature request about support for TabNavigator exists, but has not been worked on yet.
