### ISSUE TITLE
How to disable gestures on iOS?

### ISSUE THREAD

**Issue by kevinwolfcr** [fram-x/FluidTransitions#151]
I need to disable gestures on iOS, but as I see on the code, they are enabled by default if we are on that platform:

https://github.com/fram-x/FluidTransitions/blob/6797b810f36f61db10cbb8fffcb241079e295d4a/lib/FluidTransitioner.js#L244

**Comment by Krosh** [comment]
@kevinwolfcr you can set options "gesturesEnabled" as it written in documentation https://github.com/fram-x/FluidTransitions/blob/develop/docs/FluidNavigator.md#gesture-support

**Comment by kevinwolfcr** [comment]
Doesn't work, check at the code. On iOS, it will always be enabled.

**Comment by Krosh** [comment]
const gesturesEnabled = typeof options.gesturesEnabled === 'boolean'
      ? options.gesturesEnabled
      : Platform.OS === 'ios'; - if you set options.gesturesEnabled to any boolean value it's value will be used, that's wrong?

**Comment by chrfalch** [comment]
Should be working - we're using this in our customer apps. Use `navigationOptions´ and set `gesturesEnabled` to false.
