### ISSUE TITLE
Transition of an element inside a scrollView creat FOC

### ISSUE THREAD

**Issue by obsidianart** [fram-x/FluidTransitions#158]
I'm having FOC of the animated elements when inside a scrollable view (note that the banana flashes too for a moment, no idea why).
If you have a boilerplate I can happily reproduce it there as my code might be overly complicated, but conceptually:
```
// Manifest of possible screens
const PrimaryNav = FluidNavigator({
  LaunchScreen: { screen: LaunchScreen },
  Level: { screen: Level }
}, {
  transitionConfig: {
    duration: 3500,
    timing: Animated.timing,
    easing: Easing.easing
  },
  navigationOptions: { gesturesEnabled: true },
})
```

Tile on the main screen
```
        <ScrollView
          ref={ref=>{this.scrollview = ref}}
          style={{ flex: 1 }} 
          contentContainerStyle={{ width: STEP * BOARD, height: STEP * BOARD }}
          maximumZoomScale={1}
          minimumZoomScale={1}
          directionalLockEnabled={false}
          onScrollBeginDrag={() => {
            this.background.animate()
          }}
        >
          //...map
             <Tile
                key={id}
                transitionShared={`tile-${id}`}
                inline
                color={bg}
                isSolved={isSolved}
                x={x}
                y={y}
                step={STEP}
                onPress={() => {
                  this.props.navigation.navigate('Level', {id})
                }}
              />
</ScrollView>
```

Expanded tile
```
<Transition shared={`tile-${id}`} >
          <View
            style={{
              width: Dimensions.get('window').width,
              height: Dimensions.get('window').height,
              backgroundColor: bg,
              position: 'absolute',
              top: -10,
              left: 0,
              zIndex: -1
            }}
          />
        </Transition>
```

The banana in an issue with Image, it's fixed by moving to FastImage

Gif of the happy path(user didn't scroll) and unhappy path(user did scroll)

![2019-01-21 14 24 42](https://user-images.githubusercontent.com/272280/51480443-fa15c800-1d88-11e9-9c26-2456b3f84f27.gif)
![2019-01-21 14 25 14](https://user-images.githubusercontent.com/272280/51480447-fbdf8b80-1d88-11e9-8934-8e443adde0ca.gif)

**Comment by obsidianart** [comment]
After some checking I can see the "render" of each page is called twice when clicking. It seems the navigation.navigate is causing a re-rendere of the current route (this doesn't happen when using a gesture). Is this a known issue with the routing system?

**Comment by obsidianart** [comment]
I tried various way, I still have that flash :(

**Comment by obsidianart** [comment]
version 0.3 made the problem different. I'm closing this one for now and I'm going to open a separate one if I'm not able to fix it

**Comment by obiwankenoobi** [comment]
Hey! How did you fixed the flashing banana? I have the same issue.

**Comment by obsidianart** [comment]
@obiwankenoobi No, I dropped fluid transition after I realised it wasn't working well on android :(
the flash was caused by using fast-Image instead of the basic image component

**Comment by obiwankenoobi** [comment]
@obsidianart sorry to hear! :( Have you moved to something similar which you can recommend?

**Comment by obsidianart** [comment]
@obiwankenoobi I don't think there's something similar, I just made nice entering animations for now and maybe one day I'll go back to this. On IOs everything worked really nicely but on Android it was impossible
