### ISSUE TITLE
forward transitions are broken

### ISSUE THREAD

**Issue by MarianBe** [fram-x/FluidTransitions#160]
all of my transitions going to a screen are broken. Going back transitions are working as expected.
react-native: 0.58.1
react-navigation: 3.0.9
react-navigation-fluid-transitions: 0.3.0

![ezgif-5-dc7ecf364315](https://user-images.githubusercontent.com/773986/51829847-b40fb580-22ee-11e9-974c-7454bf06acd6.gif)

**Comment by MarianBe** [comment]
if i try and slow the transition it starts actually working as expected but the beginning seems very shaky
![ezgif-5-963e0cd18573](https://user-images.githubusercontent.com/773986/51829972-0cdf4e00-22ef-11e9-9738-ffa052bfa219.gif)

**Comment by chrfalch** [comment]
Hi, @MarianBe - Could you try to reproduce this in a simple snack on Expo so we can investigate?

**Comment by jacek213** [comment]
@chrfalch I have exactly the same problem.

react-navigation-fluid-transition: 0.3.1
react-native 0.57.8
react-navigation 3.0.9

**Comment by MarianBe** [comment]
i am not able to reproduce this in a new project, i will have to investigate this further on monday...maybe anyone else can reproduce this?

**Comment by jacek213** [comment]
@MarianBe any progress so far? as u can see there are quite a few people who have already encountered this

**Comment by chrfalch** [comment]
Hi all - will do a test and see if I can reproduce this during the weekend.

**Comment by MarianBe** [comment]
maybe as a reference:
"react-navigation": "^3.2.1",
"react-navigation-backhandler": "^1.2.0",
"react-navigation-fluid-transitions": "^0.3.1",
"react-navigation-redux-helpers": "^3.0.0",
"react-redux": "^6.0.0",
"redux": "^4.0.1",
"react-native-gesture-handler": "^1.0.15",
"react": "16.8.1",
"react-native": "0.58.4"

**Comment by weslley39** [comment]
Any updates?

Happening the same thing with me

```
    "react": "16.8.3",
    "react-native": "0.59.3",
    "react-navigation": "^3.6.1",
    "react-navigation-fluid-transitions": "^0.3.2",
```

**Comment by chrfalch** [comment]
Would it be possible to reproduce this in any of the example screens? It is really hard to pinpoint the problem only with some gifs. We are using Fluid Transitions in several production apps and we are not having these issues unfortunately.

**Comment by weslley39** [comment]
I solved my issue.

The problem was in the way that I got the infos from navigation.

Instead of:
```
const param = navigation.getParam('item', {});
```

Changed for direct access:

```
const { item = {} } = navigation.state.params;
```

and this solved the problem for me
