### ISSUE TITLE
Is that possible to update appear dynamically?

### ISSUE THREAD

**Issue by changLiuUNSW** [fram-x/FluidTransitions#173]
I have a user case that need to update appear from 'top' to 'bottom' based on some conditions.
I have tried to store appear value as state with give initial value to 'top' and update to 'bottom' with ```this.setState``` based on some condition later, but it does not work at all.
Is that possible to dynamically set appear/disappear?

**Comment by chrfalch** [comment]
You could try providing your own transition function instead of the strings "top"/"bottom"
