### ISSUE TITLE
How to enable gesture handler in android?

### ISSUE THREAD

**Issue by FelipeBohnertPaetzold** [fram-x/FluidTransitions#182]
I have a FluidNavigation with card mode and gestures enabled. In iOS, the gesture handler works fine, but on Android devices it does not respond.

My config options are like this:

```js
createFluidNavigator(
    {...myScreens},
    {
      navigationOptions: {
        gesturesEnabled: true,
        gestureResponseDistance: {
          horizontal: 50,
          vertical: 0
        }
      },
      mode: 'card'
    }
)
```

How can i make the gesture handler work on android as well?

**Comment by PeterH139** [comment]
Just came across this bug as well but in the opposite direction: I want to disable gestures on iOS. Looks like there's a bug in `createFluidNavigator.js`: react-navigation@3.0.0 renamed 'navigationOptions' to 'defaultNavigationOptions' when defining them at the Navigator level, so they are not being passed down with the correct name.

I don't have time today, but I'll submit a PR for this on Monday.
