### ISSUE TITLE
Shared transition doesn't work on navigation reset

### ISSUE THREAD

**Issue by justinushermawan** [fram-x/FluidTransitions#184]
Transition works perfectly when I use navigate push `NavigationActions.navigate({routeName, params})`, but it doesn't when I use navigation reset method:

```
const resetAction = StackActions.reset({
  index: 0,
  actions: [
    NavigationActions.navigate({routeName, params})
  ]
});
_navigator.dispatch(resetAction);
```
I use Transition shared='...'. Is it a bug?

**Comment by chrfalch** [comment]
I don't think reset is currently supported - you need to go back/forth one page at a time.
