### ISSUE TITLE
Gestures 

### ISSUE THREAD

**Issue by jrwpatterson** [fram-x/FluidTransitions#187]
Hey quick question.

For one of our pages our marketing department what both left to right as a close gesture but also top to bottom swipe

Is that possible?

**Comment by chrfalch** [comment]
Yes, see the Stack Navigator (in React Navigation) for details on how to set gesture direction. You can also check out the examples folder in the repo - The FlatList example uses top/down-swipe to close, while the Onboarding example uses right/left.

**Comment by jrwpatterson** [comment]
but is this possible to have both at the same time on the same scene

**Comment by chrfalch** [comment]
Ah.. I don't think so? Is this supported in the Stack Navigator in React Navigation?

**Comment by jrwpatterson** [comment]
To be honest I don’t know I was looking at the code and it doesn’t appear possible but it’s a requirement that our marketing department has given me!

**Comment by chrfalch** [comment]
Should be possible to clone the repo and see if you can find a solution?

**Comment by jrwpatterson** [comment]
Sadly I think it might be too big a change... it might be something for post release
