### ISSUE TITLE
Transition within shared

### ISSUE THREAD

**Issue by RWOverdijk** [fram-x/FluidTransitions#189]
I'm trying to transition a component within a shared transition. It works, but the original seems to also stay. I believe this is because the component gets copied to get the transition to work.

For context, it's a bottom bar that needs to persist but its content needs to transition between screens.

Am I missing something and/or is this possible?

**Comment by benceg** [comment]
Try adding the [`inline`](https://github.com/fram-x/FluidTransitions/blob/develop/docs/Transition.md#inline) property to your `Transition` elements.

**Comment by RWOverdijk** [comment]
:o I forgot about this completely. I somehow solved it so eh. But for future googlers: woooooo.

kbye
