### ISSUE TITLE
Not working in real device Android

### ISSUE THREAD

**Issue by ashokkumar88** [fram-x/FluidTransitions#19]
I integrated the Fluidnavigator between two screens and it is working fine in Genymotion  (emulator). But when i test it in a real Android device it is not working at all. It is simply cross fades.

**Comment by ashokkumar88** [comment]
@chrfalch I tried the Example app and it is working fine in real device also. May be some issue with my code. I will check. Thanks

**Comment by chrfalch** [comment]
Ok, sounds like you'll solve this one! I'll close the issue for now.
