### ISSUE TITLE
Support for React Navigation 2.x

### ISSUE THREAD

**Issue by fabriziogiordano** [fram-x/FluidTransitions#2]
Great library.
Is there a plan to support React Navigation 2.x
https://next.reactnavigation.org/docs/en/stack-navigator.html

Few API will change `StackNavigator` becomes `createStackNavigator`.

Is there a way to help?

**Comment by ericvicenti** [comment]
Hey @chrfalch, great work! I actually came here to post about the same topic, react-nav 2 and beyond.

### v2

We've updated the API for createNavigator in v2, which will make your migration slightly non-trivial, but it should result in simpler code. The new API is documented here:

https://next.reactnavigation.org/docs/en/custom-navigators.html#createnavigator 

tldr: the navigation view now gets screen 'descriptors', and no longer can directly access the router. addNavigationHelpers is going away.

### v3 and beyond

Let's collaborate on a new transitioner for the library! The one in core is pretty crufty, as I'm sure you've realized 😆 

I'm drafting a simpler new transitioner here, potentially for v3 of the library: https://github.com/react-navigation/react-navigation/blob/%40ericvicenti/transitioner2/src/views/StackView/Transitioner2.js

But it doesn't support your shared element magic, so I think this would be great timing to collaborate.

It would be so nice to allow the header and inner elements to be rendered via shared element transition in comparison to the current approach. We'd be able to support much more advanced use cases. Plus, navigation options have proven to be a pretty inconvenient way for people to set up their header in comparison to rendering things inside the screen, where component state can be accessed.

Feel free to message me on twitter, or email <my github handle> at gmail.

**Comment by chrfalch** [comment]
@ericvicenti - I'll message you later :-)

@fabriziogiordano - I don't think it would be too difficult to upgrade the library to V2!

**Comment by chrfalch** [comment]
@ericvicenti Please email me at christian.falch at gmail.com so that we can discuss directly :-)

**Comment by joegoodall1** [comment]
Hi @chrfalch,

Echoing @fabriziogiordano and @ericvicenti comments, found this to be a really good library which works seamlessly with react-navigation v1.x.

Any update on future support for v2 and v3?

**Comment by chrfalch** [comment]
@joegoodall1 I haven't had the time to start looking at the new versions, wanted to get the existing version up to a descent level first ;-)

**Comment by chrfalch** [comment]
Done!
