### ISSUE TITLE
performance is very slow :/

### ISSUE THREAD

**Issue by ODINA101** [fram-x/FluidTransitions#20]
https://snack.expo.io/rJPiLbzTG

**Comment by chrfalch** [comment]
@ODINA101 Thanks for your issue. From what I can see it doesn't look like its using Transitions at all, please provide a working snack (https://snack.expo.io) that highlights the issue you are experiencing.

**Comment by ODINA101** [comment]
thank you bro for response but problem was from me sorry for it  <3

**Comment by chrfalch** [comment]
That's fine :-)
