### ISSUE TITLE
The image zooms during Transition between screens

### ISSUE THREAD

**Issue by vedant17** [fram-x/FluidTransitions#201]
The image is zooming when I try to move between pages. 

This is my code of two pages.

Screen 1:

```
<Transition shared="logo">
       <Image source={require('../Assets/Dobby_Logo.png')}
       style={{width: 100, height: 140}}/>
</Transition>
```

Screen 2:

```
<Transition shared="logo">
      <Image source={require('../Assets/Dobby_Logo.png')}
      style={{width: 50, height: 70, marginTop: 15, marginLeft: (0.15  * screenWidth), alignSelf: 'flex-start'}}/>
  </Transition>
```

The image is zooming to it's full size during transition. How to solve this issue?

**Comment by xxRockOnxx** [comment]
In my case I just wrapped the `Image` in a `View` and it works.
It needs a container so that the computed width/height of an image is still relative to the container.
