### ISSUE TITLE
Using Transition inside map method cause wrong transition

### ISSUE THREAD

**Issue by thecoorum** [fram-x/FluidTransitions#205]
**Problem Description**
I'm using `<Transition>` inside map method that renders components from received data, to move from Main screen to Details screen

`Home.js`
```
{/* ... */}
<ScrollView>
   {this.state.data.map(el => {
      return(
         <Transition shared="card">
            <Card />
         </Transition>
      )
   })}
</ScrollView>
{/* ... */}
```

`Details.js`
```
{/* ... */}
<Transition shared="card">
   <Card />
</Transition>
{/* ... */}
```

**Expected Behavior**
On tapping on card it will move to exact position on `Details.js`

**Actual Behaviour**
The transition is always starting from first element in `<ScrollView>` and on back navigation returns to it, despite on selected `<Card />` component

**Comment by tberman** [comment]
I think this is to be expected, you likely need to include some kind of id in the name both in Home and in Details so that the names continue to match.
