### ISSUE TITLE
noob question - failed to load bundle  

### ISSUE THREAD

**Issue by johndpope** [fram-x/FluidTransitions#21]
yarn install v1.6.0

brew install yarn
clone repo
cd Examples
yarn
react-native run-ios

![screen shot 2018-05-02 at 14 54 52](https://user-images.githubusercontent.com/289994/39543331-ddd3d4d8-4e18-11e8-990b-ac99575ffd29.png)

![screen shot 2018-05-02 at 14 56 02](https://user-images.githubusercontent.com/289994/39543361-f872784e-4e18-11e8-82ae-cb0ee0e05660.png)

I end up with 
node_modules in the root folder
and node_modules in the Example folder.
NB - I only cd straight into Examples folder
I tried yarn cache clean to no avail.

**Comment by chrfalch** [comment]
You don't need to yarn in the root directory, as the Readme says:

>To start the example, navigate to the examples folder and run the following commands from the terminal:
npm i or yarn
To start the project run
react-native run-ios or react-native run-android

**Comment by johndpope** [comment]
for some reason yarn seems to be creating it there irrespectively.
yarn install v1.6.0.

**Comment by johndpope** [comment]
Hi @chrfalch  - are you using nvm /with a specific version of node? this ticket looks similar https://github.com/Microsoft/react-native-code-push/issues/1197

**Comment by johndpope** [comment]
![screen shot 2018-05-03 at 15 53 24](https://user-images.githubusercontent.com/289994/39599566-2310c142-4eea-11e8-8ecd-c5ce44917787.png)
