### ISSUE TITLE
White transition screen. 

### ISSUE THREAD

**Issue by samuelgjabel** [fram-x/FluidTransitions#24]
I dont know if this is bug or just not implemented (future request)?
But if you use fluid navigator and inside it you want to pass other stacknavigator ->
navigation transition beetween these screens is white.

Simply put:
Navigate from fluidNavigator to Stacknavigator -> whole transition is white -> after transition ends -> resolve new screen and white disappear.  :)

**Comment by chrfalch** [comment]
Hi @samuelgjabel! Thanks for reporting the issue. The FluidNavigator is not ment to be used with nested navigation structures where it holds other navigators - only for transitions between screens.
