### ISSUE TITLE
Doesn't play nice with styled components

### ISSUE THREAD

**Issue by sonaye** [fram-x/FluidTransitions#25]
I found that this library renders glitchy animations when using `styled-components`, `glamorous-native` or a custom styled components API, switching to the typical way of writing styles in RN fixes things. I wrote a light custom styled-components-like function to do some debugging.

![kapture 2018-05-11 at 14 21 48](https://user-images.githubusercontent.com/23000873/39922204-a8b61f8a-5526-11e8-84e9-8ea93410c700.gif)

Top: Not using styled components.
Bottom: Using styled components.

Code to reproduce available [here](https://github.com/sonaye/fluid-transitions/blob/dev/src/Bug.js).

**Comment by chrfalch** [comment]
I think I know what's going on here... The interpolator system needs to get information about the items from somewhere, and that somewhere is the style property. When providing function based components the style is not available until the item function has been called. This will result in the issue you are having with the background color.

The other thing the example shows is the strange size transition - that should not look like what you see and I'll take a look at it and see what if I can find out what's going on.

**Comment by chrfalch** [comment]
If you add the following style to the outer container view, the size transition seems to be working:

```
<View style={{ flex: 1, justifyContent: 'flex-start', alignItems: 'flex-start' }}>
```

The problem seems to be that the `UIManager.measureInWindow` function returns the wrong size for the elements without this style. This might have something to do with the `createAnimatedWrapper` function I'm using and I'll keep on investigating this.

**Comment by dcvz** [comment]
I've seen similar things happen when you have items that take up percentage width. My fix has usually been to insert an invisible item that has the window width, but it'd be great for the library to be able to replicate the parent's window.

**Comment by sonaye** [comment]
> The interpolator system needs to get information about the items from somewhere, and that somewhere is the style property

@chrfalch This explains it. Maybe we can fix this by adding a `defaultStyle` prop to `<Transition />` which -if provided- forwards the styles to the interpolator. Then as a user I can add a HOC that injects `defaultStyle` to every styled components used (since this is left to the user, adding a `defaultStyle` prop is enough).

**Comment by sonaye** [comment]
@dcvz In general, animations in React Native don't work well with percentages (typically they would throw).

**Comment by sonaye** [comment]
Revisiting this again I think supporting styled components is not an essential thing to have, I like the direction the development is going, let's keep it that way for now.

**Comment by chrfalch** [comment]
@sonaye The last version in develop now supports retrieving rendered props from components like the one you wrote - just mentioning it you'd like to try :-) Haven't released it yet.

**Comment by lXSPandora** [comment]
Can we re-open this because still not working nice with styled components @sonaye @chrfalch
