### ISSUE TITLE
Gestures direction is invalid

### ISSUE THREAD

**Issue by sonaye** [fram-x/FluidTransitions#26]
Is this the intentioned behavior? shouldn't it be from the left?

<img src="https://user-images.githubusercontent.com/23000873/39924361-1f30e920-5530-11e8-91dd-c230b30aea33.gif" width="400">

Code to reproduce available [here](https://github.com/sonaye/fluid-transitions/blob/master/src/index.js).

**Comment by chrfalch** [comment]
Hi @sonaye, thanks again. If you are referring to the code snippet on [line 56](https://github.com/sonaye/fluid-transitions/blob/master/src/index.js#L56):
´´´<Transition appear="left">

**Comment by sonaye** [comment]
The default gesture to go back to the previous screen in StackNavigator is to swipe from the left edge (iOS). In FluidNavigator (based on StackNavigator as I understand) swiping from the left edge doesn't work at all, instead swiping down (anywhere in the example) is the active gesture.

> The gesture only interpolates the same animation as the one used transition in.

It doesn't feel right though, my workaround was to disable all gestures which is not ideal. Maybe it make sense to have this behavior in some scenarios (I'm sure you encountered some which is why you adopted it in the first place). Maybe we can add an option to keep the default gestures, `FluidNavigator({ ... }, {  keepDefaultGestures: true })`?

**Comment by Un3qual** [comment]
@sonaye from the docs:

To change the direction (default is vertical), set the mode to `card` | `modal`:

```javascript
const Navigator = FluidNavigator({
  ...
}, {
  mode: 'card' // Horizontal gestures
});
```
