### ISSUE TITLE
How to know when transitions are finished?

### ISSUE THREAD

**Issue by Un3qual** [fram-x/FluidTransitions#27]
I have a screen with a `TextInput` that I want to call `.focus()` on, but only after the transition animations have finished. Is there a way to do that? I tried using `didFocus`, but that doesn't get called (possibly related to #9). `willFocus` gets called, but it happens too early. `react-navigation`'s `.isFocused()` returns `true` too early.

**Comment by Un3qual** [comment]
After poking around a bit, I may have found some bugs, but I'm not totally sure because I don't know a ton about the internals of this repo. The main issues that I've found are in `FluidNavigator.js`. Here, https://github.com/fram-x/FluidTransitions/blob/0efb79579e48ce4b59e94db47efbe0a8636bf571/src/FluidNavigator.js#L19
you assign `onTransitionStart` and `onTransitionEnd` from `stackConfig`, but when creating the `FluidTransitioner` component, you use `this.props.onTransitionStart`, which is undefined. Those should be switched to just `onTransitionStart`, and here https://github.com/fram-x/FluidTransitions/blob/0efb79579e48ce4b59e94db47efbe0a8636bf571/src/FluidNavigator.js#L40 you reassign `onTransitionEnd`, so that should just be removed from that line. Next, in `FluidTransitioner.js`, `onTransitionEnd={this.props.onTransitionEnd}` should be added below https://github.com/fram-x/FluidTransitions/blob/0efb79579e48ce4b59e94db47efbe0a8636bf571/src/FluidTransitioner.js#L74
Finally, `_onTransitionStart` doesn't ever call `this.props.onTransitionStart()` (i don't think), so that should be added. I'm not sure where though because the `_onTransitionStart` with the promise is a little confusing.

I can submit a PR for the rest of this, I just want to confirm that these are actually issues and aren't intentional.

**Comment by chrfalch** [comment]
Sorry for the late reply, @Un3qual, and thanks for the feedback! This is obviously wrong and should be corrected - thanks for noticing - and yes - please provide a PR if you want to.

**Comment by rhbarauna** [comment]
@chrfalch, @Un3qual  any news about that?
