### ISSUE TITLE
transitionConfig not working in FluidNavigator 2.0

### ISSUE THREAD

**Issue by kkbhav** [fram-x/FluidTransitions#28]
Hi, I tried to implement transitionConfig as mentioned in the readme. But I am not able to get it to work for me. Can you please check it.

My config looks like this:
```
{
  mode: 'card',
  navigationOptions: {
    gesturesEnabled: true,
    gestureResponseDistance: {
      horizontal: 100,
      vertical: 100,
    },
  },
  transitionConfig: {
    duration: 1500,
    timing: Animated.timing,
    easing: Easing.linear(),
    useNativeDriver: true,
  },
}
```

Thanks

**Comment by Un3qual** [comment]
Could you explain what's not working? Do you get an error message? Do you get any unexpected behavior?

**Comment by ronal2do** [comment]
duration is not working

**Comment by BenoitClaveau** [comment]
How can I modify the duration of the transition ?

**Comment by ranadeep47** [comment]
https://github.com/fram-x/FluidTransitions/blob/develop/src/createFluidNavigator.js#L35
`transitionConfig` is not being passed as a prop here. 

But an alternative way to pass screen specific transition config according to 
https://github.com/fram-x/FluidTransitions/blob/develop/src/FluidTransitioner.js#L113
is to put `transitionConfig ` in `navigationOptions` of the screen. 

The actual fix would be to pass `transitionConfig` from https://github.com/fram-x/FluidTransitions/blob/develop/src/createFluidNavigator.js#L18 as a prop to `FluidTransitioner `

**Comment by BenoitClaveau** [comment]
thanks @ranadeep47 works with
`static navigationOptions = {
        transitionConfig: {
            duration: 350,
            timing: Animated.timing,
            easing: Easing.inOut(Easing.poly(4)),
            useNativeDriver: true,
        },
    }`

**Comment by kkbhav** [comment]
Yes, this seems to work.  
But this seems like a very long way of implementing **transitionConfig** to a whole group of screens. Implementing it on every screen is also very hard to maintain.  

Will there be a implementation of transitionConfig in the navigator function in the near future?
