### ISSUE TITLE
Expect nav state....

### ISSUE THREAD

**Issue by ducpt2** [fram-x/FluidTransitions#3]
When i use FluidNavigator to replace StackNavigator, i created a nested navigation(Tab in Stack, Stack in Drawer) and got a issue: 
 - Expect nav state to have routes and index, {"routeName":"Main","key":"Init"}

If i change Tab to a screen, it work fine. :) with FluidNavigator.

Any help? Thanks

**Comment by ducpt2** [comment]
i tried using your Example to reproduce my issue. Finally, i got it work by that:
- Change 
TabsNav: {
    screen: TabsNav,
  }
to: 
TabsNav: {
    screen: (() => <TabsNav />),
  }
But i can not see my Header of my Stack? How this happen?
Can you help me pls? Really want using this library. Thanks 👍

**Comment by chrfalch** [comment]
I'm not sure why this happens - feel free to fork this project and see if you can find something that could help!
