### ISSUE TITLE
Transitioning Text Changes

### ISSUE THREAD

**Issue by dcvz** [fram-x/FluidTransitions#30]
I have a `<Text />` and a `<Button />` that are present across two screens. The animation between the two positions works well. However these two components also have text that changes.. and the change in text doesn't happen until the animation is complete, which makes it look a bit odd (jumpy). Is there any way to allow the texts to fade in and out as the position translation happens?

**Comment by chrfalch** [comment]
Text styles are not interpolated in the library due to some technical issues - others have asked for the same and I'll mark this one as a feature request for future reference.

**Comment by sanjaymhj** [comment]
Is the text component re-drawn on each screen transition?

**Comment by sanjaymhj** [comment]
Please do correct if this issue does not belongs here.

I guess the Text is redrawn in each screen transition.

***Scenario:***
A text bound by a view.
Both screens have the same component, except the width of the enclosing view(width is different).
While transition between two screens, the transition of text does not go as expected.

![text transition](https://user-images.githubusercontent.com/3464203/42218367-0d785dd0-7ee8-11e8-83e9-281d1d004c0e.gif)

***Steps to recreate issue:***
This can be recreated every time with the [LayoutTransition from example](https://github.com/fram-x/FluidTransitions/blob/develop/Examples/src/LayoutTransition.js) with following changes:
1. Change text to include only one word.
2. Change one of the textContainer to textContainer2
3. Change the width of textContainer and textContainer2 to 100 and 200 (or sth different).

For convenience here is the final code.
`import React from 'react';
import { View, Text, Button, ScrollView, Dimensions, Image, StyleSheet } from 'react-native';

import { FluidNavigator, Transition } from 'react-navigation-fluid-transitions';

const styles = StyleSheet.create({
  container: {
    padding: 20,
  },
  screen: {
    flex: 1,
    flexDirection: 'row',
    padding: 20,
  },
  buttonContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: '#EDEDED',
    marginBottom: 20,
  },
  buttonRotatedContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    transform: [{ rotate: '180deg' }],
    backgroundColor: '#EDEDED',
    marginBottom: 20,
  },
  textContainer: {
    width:100
  },
  textContainer2: {
    width: 200
  },
  image: {
    width: Dimensions.get('window').width - 40,
    height: (Dimensions.get('window').width - 40) * 0.5,
  },
  smallImage: {
    width: (Dimensions.get('window').width - 45) * 0.5,
    height: ((Dimensions.get('window').width - 45) * 0.5) * 0.5,
  },
  imageContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 14,
    paddingBottom: 14,
  },
  header: {
    fontWeight: 'bold',
    fontSize: 20,
  },
});

const InitialScreen = (props) => (
  <ScrollView contentContainerStyle={styles.container}>
    <Transition shared="buttons">
      <View style={styles.buttonContainer}>
        <Button title="Toggle" onPress={() => props.navigation.navigate('screen')} />
      </View>
    </Transition>
    <Text style={styles.header}>Lorem ipsum</Text>
    <View style={{ height: 15 }} />
    <Transition shared="text1">
      <Text style={styles.textContainer}>
        Lorem
      </Text>
    </Transition>
    <View style={{ height: 15 }} />
    <Transition shared="image1">
      <Image source={{ uri: 'https://picsum.photos/200/100?image=12' }} style={styles.image} />
    </Transition>
    <View style={{ height: 15 }} />
    <Transition shared="text2">
      <Text style={styles.textContainer}>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus condimentum
        magna ut tortor vehicula tincidunt. Vestibulum nisi libero, lacinia ac consequat id,
        porttitor ac nisi. Praesent luctus ex sem. Integer vel elit eleifend, semper enim ut,
        euismod arcu.
      </Text>
    </Transition>
    <View style={{ height: 15 }} />
    <Transition shared="image2">
      <Image source={{ uri: 'https://picsum.photos/200/100?image=22' }} style={styles.image} />
    </Transition>
  </ScrollView>
);

const Screen = (props) => (
  <ScrollView contentContainerStyle={styles.container}>
    <Transition shared="buttons">
      <View style={styles.buttonRotatedContainer}>
        <Button title="Toggle" onPress={() => props.navigation.goBack()} />
      </View>
    </Transition>
    <Transition shared="text1">
      <Text style={styles.textContainer2}>
        Lorem
      </Text>
    </Transition>
    <View style={styles.imageContainer}>
      <Transition shared="image1">
        <Image source={{ uri: 'https://picsum.photos/200/100?image=12' }} style={styles.smallImage} />
      </Transition>
      <Transition shared="image2">
        <Image source={{ uri: 'https://picsum.photos/200/100?image=22' }} style={styles.smallImage} />
      </Transition>
    </View>
    <Transition shared="text2">
      <Text style={styles.textContainer}>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus condimentum
        magna ut tortor vehicula tincidunt. Vestibulum nisi libero, lacinia ac consequat id,
        porttitor ac nisi. Praesent luctus ex sem. Integer vel elit eleifend, semper enim ut,
        euismod arcu.
      </Text>
    </Transition>
  </ScrollView>
);

const Navigator = FluidNavigator({
  home: { screen: InitialScreen },
  screen: { screen: Screen },
});

class LayoutTransitions extends React.Component {
  static router = Navigator.router;
  render() {
    return (
      <Navigator navigation={this.props.navigation} />
    );
  }
}

export default LayoutTransitions;
`

**Comment by chrfalch** [comment]
Hi @dcvz! Thanks for submitting an issue. Fluid Transitions does not currently support transitioning text changes. This is currently a feature request in issue #30. Closing this one for now.
