### ISSUE TITLE
several react-native 

### ISSUE THREAD

**Issue by HamidReazaNikoonia** [fram-x/FluidTransitions#31]
actually this is not Issue , but maybe be an issue
because  i am new in react native

myQ : i want run Example code from repo

this is my way for implement 
 1-  clone repo
 2- cd Example
 3- npm i

after run "react-native run-android" command , i give the error about undefined and cant resolve 'react'  in this path ( src/utils/createAnimatedWrapper.js ) , after this error 

im back to root folder
    cd ..
and then
    npm i 
for install dependency in package.json in root folder not in example folder

after that i give error again and this is the error

![image](https://user-images.githubusercontent.com/24862548/39962038-26369362-5659-11e8-95cb-03631bd1eeba.png)

please help me 

Note : i run " react-native run-android " this command in Example folder not in root

**Comment by HamidReazaNikoonia** [comment]
and include this to my question

after this error ,  i do this way but not help me and again give this erro

rm -rf node-module
watchman 
npm i

**Comment by chrfalch** [comment]
Hi @HamidReazaNikoonia! You shouldn’t need to run NPM in the root folder, only in the example folder. Another way to test the library is to create a new project and copy some of the example code (remember to npm install react-navigation and react-navigation-Fluid-transitions).
