### ISSUE TITLE
Error on nested elements

### ISSUE THREAD

**Issue by zivchen** [fram-x/FluidTransitions#32]
Hi
When trying to add your plugin to my navigation system i get the following error:

> 
> Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
>     in Unknown (at createNavigationContainer.js:226)
>     in NavigationContainer (at SceneView.js:17)
>     in SceneView (at ResourceSavingSceneView.js:55)
>     in RCTView (at View.js:60)
>     in View (at ResourceSavingSceneView.js:48)
>     in RCTView (at View.js:60)
>     in View (at ResourceSavingSceneView.js:39)
>     in ResourceSavingSceneView (at TabView.js:35)
>     in RCTView (at View.js:60)
>     in View (at TabViewPagerPan.js:251)

My structure is different then the regular example so maybe it has something to do with it.
StackNavigator (parent)=>TabNavigator (First child) => StackNavigator(second child)

The screens that i want to "fluid" are inside the second child stack.
When I change just the second StackNavigator to FluidNavigator i get the error above.

If im changing both StackNavigator to FluidNavigator i get a different error:
> ExceptionsManager.js:71 Unhandled JS Exception: TypeError: Cannot read property 'getStateForAction' of undefined
> 
> This error is located at:
>     in NavigationContainer (at edocate.js:68)
>     in Provider (at edocate.js:64)
>     in RCTSafeAreaView (at SafeAreaView.ios.js:34)
>     in SafeAreaView (at edocate.js:56)
>     in Edocate (at renderApplication.js:33)
>     in RCTView (at View.js:60)
>     in View (at AppContainer.js:102)
>     in RCTView (at View.js:60)
>     in View (at AppContainer.js:122)
>     in AppContainer (at renderApplication.js:32)

Thanks

**Comment by chrfalch** [comment]
Hi @zivchen! Thanks for submitting the issue! 
FluidNavigator does not support transitions with nested navigators beneath itself. It only supports transitions between screens as components - transitioning with sub navigators does not make sense. 

If you still believe that you have a valid use case, please create a really small repo using snack.expo.io that shows what you want to accomplish and why.

**Comment by zivchen** [comment]
Hi 
Since upgrading react-navigation to v2 the problem seems to go away.
Closing
