### ISSUE TITLE
Missing support for passing props with ScreenProps

### ISSUE THREAD

**Issue by benjaminwaterlot** [fram-x/FluidTransitions#35]
Hello there,
 
First I wanted to thank you for the work you're doing on FluidTransitions which is really amazing.

I'm having an issue which I think is related to FluidNavigator being not as "complete" as createStackNavigator, nor as the (deprecated) _StackNavigator_ which currently supports screenProps. 

## The issue
You should be able to **pass the prop ScreenProps** to FluidNavigator so that every children have access to it, like this (adapted from the [docs of createStackNavigator](https://reactnavigation.org/docs/en/stack-navigator.html#navigator-props)) : 

```
const SomeStack = FluidNavigator({
  // config
});

<SomeStack
    screenProps={{name: 'John'}}
    // this prop will get passed to the screen components as this.props.screenProps
  />

// In your children component :
return <Text> Hello {this.props.screenProps.name} ! </Text>
```

## Current behavior
Currently this code generate an error because **screenProps is *undefined*** in the children component.
It should instead refer to the object we passed into FluidNavigator as **"screenProps"**.

This was my first issue on GitHub so apologizes if I'm doing something wrong 😺

Thanks again,
Benjamin

**Comment by chrfalch** [comment]
Thanks for the issue, @benjaminwaterlot :-)
