### ISSUE TITLE
Cancellability / External Animation Driver Questions

### ISSUE THREAD

**Issue by solomonhawk** [fram-x/FluidTransitions#38]
Hi, thanks for sharing this work. I found my way here via https://github.com/react-navigation/rfcs/issues/17.

I haven't taken a super close look at the code here, but I am curious whether you designed this implementation with the following use cases in mind:

1. Cancelling a transition (e.g. if your app may programmatically trigger navigation events.. possible to different places within a short period of time)
2. Driving a transition via user touch events (e.g. a PanResponder) or by some other `Animated.Value` or `Animated.SrollView`

I hope these questions are sensible!

**Comment by chrfalch** [comment]
Hi @solomonhawk!

1. We're using the `Transitioner` class in React Navigation which handles queuing of navigation requests. 
2. Support for transitioning using a PanResonder is already added. Only as a linear animation, none of the elements follows your touch yet, it only interpolates the shared element transition. It has been discussed if it is possible to drive the animation from an outside `Animated.Value` (like from a ScrollView), but a good use case is needed.

**Comment by solomonhawk** [comment]
@chrfalch Neat! Thanks for the prompt follow up. 

Maybe a use case for the Animated Value driven transition would be a sort of "peek" preview that also includes a shared element transition.. seems kind of dubious though (but could make sense in the context of certain kinds of custom transitions). I'll have to think on it more.

Cheers

**Comment by chrfalch** [comment]
I'll close this one for now - please reopen or submit a new issue with a feature request including the use case - this might be a great idea; we just need the story to back it up :-)
