### ISSUE TITLE
Use transitions in a swiper of images

### ISSUE THREAD

**Issue by 4l3nc** [fram-x/FluidTransitions#40]
I'm using the FluidTransitions in a swiper of images, so I only see one image at a time. This first image is working very well making the transition of the image to another screen, the problem is when I pass to the next image in the deck, then the transition animation is not working, I don't know why because I'm rendering the card one by one:

``
renderCard = (card, index) => {
    return (
                    <TouchableHighlight onPress={() => navigate(DETAIL)}>
                        <Transition shared="image">
                            <Image source={card.image} />
                        </Transition>
                    </TouchableHighlight>
        )
};
``

Do you know why is only working with the first card in the deck? The next card is rendered below the previous. I made my own swiper and with other libraries and the result is the same. Probably is not fault of your library but I wasted all my ideas.
Thanks.

**Comment by chrfalch** [comment]
Hi @4l3nc! Thanks for submitting an issue. Please create a simple reproduction using https://snack.expo.io.

**Comment by 4l3nc** [comment]
Hi again! I tried to reproduce the same problem in snack.expo but for some reason the library that I used for the card doesn't work for some errors with lodash 😢 

So I used another one with the same effect but I get a different problem, all the cards makes the fluid navigation when you click over the image except the last one, in my project for example only works the first one:

https://snack.expo.io/Sklthghgm

If you add more cards you will see that the last one doesn't work properly.

The main different between the library I used on expo and in my proyect is that the component has some method for render each card like I said in my first message and in this case all the cards are in the children of the component.

If you need more details just tell me.

**Comment by 4l3nc** [comment]
I believe that you leave the wrong label in the issue, I actually made the example 😃

**Comment by chrfalch** [comment]
@4l3nc Sorry, label removed ;-)

**Comment by chrfalch** [comment]
Have you tried to use unique ids for the shared property? They all have the same id: logo - maybe using an index or id would help? You can see how this was done in the Image transition example.

**Comment by 4l3nc** [comment]
I had the same result:

https://snack.expo.io/HJtp0GVbm

**Comment by chrfalch** [comment]
Hi @4l3nc! I've tested your project and I'm seeing the same as you. After debugging it I could see that the swiper library uses a few hacks to display the card stack, causing not all cards to call their correct `componentDidMount` functions - leading to missing registration in Fluid Transitions. This is probably nothing I can solve directly in this library, so I'm closing this issue.
