### ISSUE TITLE
Feature: Opacity/Fade-in/out transitions

### ISSUE THREAD

**Issue by arielwb** [fram-x/FluidTransitions#41]
Hi, thanks for the awesome library! 

I'm testing it out, and I'm having difficult animating components that require nested Transition elements.

Is this behaviour possible?

What Im trying to achive:
Moving a container down and an element inside of it, up :P

If I dont nest the elements, I would have to track sizes and positions of absolutely positioned elements, and I'm trying no to go down that road.

Here's a snack with some sample code: 
https://snack.expo.io/@arielwb/nested-fluid-transitions-

Screen 1 to 2
transitions are ok, no nested Transitions

Screen 3 to 4
Only in the the first run of the animation behaves correctly.

I tried different combinations of style props (transform, top, position), and it seems that this is not the problem.

Any suggestion it would be much appreciated!
Thanks ;)

**Comment by chrfalch** [comment]
Hi @arielwb! Thanks for posting the issue with a good sample! Nested transitions are not supported due to the complexity it creates. However, a feature request about a new animation property is on its way (#37 Shared Element Morphing) that might help solve your task.

**Comment by arielwb** [comment]
Hi, thanks for the quick reply!
I will check out the other feature request  ;)

In the mean time, I'm trying to make things work without nesting the transitions,
I guess it will work ok for my use case.

While I have your attention I'd like to ask, is there a way to do a simple fade in/out?
I saw that we have some predefined transition types to use with the appear/disappear prop, but no fade.

I know that I can achieve this using custom transitions, but I feel that its such a basic use case that maybe I'm missing something.

Thank you again for your time!

**Comment by chrfalch** [comment]
Hi @arielwb! Thanks for your feedback :-) 

Fade in/out is the default transition; haven't had the time to make it explicit - would you try to create one or two use cases (shared elements or transitions etc).

**Comment by chrfalch** [comment]
I'm closing this one. The default transition is a fade in/out transition, so a snippet like the following would fade in/out elements:

```jsx
<Transition>
  <Text>This is cool stuff</Text>
</Transition>
```

**Comment by fendorio** [comment]
If it is the default transition, how do you apply it to the dissapear transition, as doesn't that use the animation supplied to appear? 

Problem: How to fade out on disappear when appear transition is set?

**Comment by chrfalch** [comment]
It's unfortunately not possible to combine transitions yet, but you should be able to build your own - there should be a small example in the docs on how to do this, and you should be able to look at the existing transitions and copy some code.
