### ISSUE TITLE
FlatList example

### ISSUE THREAD

**Issue by jskidd3** [fram-x/FluidTransitions#43]
Firstly thank you for putting together such a neat library.

I imagine it's because this example is outdated, but see the video below for what happens when you run the code in `Examples/src/FlatList.js`. The image appears to revert back to its original size.

Any help would be gratefully received!

![Video showing bug](https://i.imgur.com/kQsH3Xd.gif)

**Comment by jskidd3** [comment]
I can't seem to reproduce this in a Snack with pretty much the exact same code with the same `package.json`. Any ideas what could be causing this?

**Comment by jskidd3** [comment]
It's amazing the things that can set you back. I had an import called `Image` from another library (scalable-image) which caused this.

**Comment by ducpt2** [comment]
@jskidd3  does it work well on android, in my android emulator, the image zoom out is not smooth like ios.
