### ISSUE TITLE
allow configuring swipe direction per-screen

### ISSUE THREAD

**Issue by Talor-A** [fram-x/FluidTransitions#49]
hi, in my app I'd like to change the swipe direction to be `modal` on some screens and `card` on others. is this possible?

**Comment by chrfalch** [comment]
Yes, each screen can have its own `navigationOptions` value - just like when you set up a StackNavigator.

**Comment by RWOverdijk** [comment]
@chrfalch What would that look like? I tried adding this, but I still have to close my modal from left to right:

```js
  static navigationOptions = {
    mode: 'modal',
  };
```

**Comment by RWOverdijk** [comment]
According to this: https://reactnavigation.org/docs/en/modal.html

It needs to be on the stack. But I have shared Transitions and lose the effect when doing so.
