### ISSUE TITLE
Findings on the performance

### ISSUE THREAD

**Issue by narendrashetty** [fram-x/FluidTransitions#5]
I went through the code and it's some really good implementation by @chrfalch :)

I extended the example mentioned here and simulated it to make a busy app to test out how smooth  SET would be.

Here are the screen recording of 2 instance.

1. using `useNativeDriver` (https://media.giphy.com/media/AS4NAijk6WVGaslJOW/giphy.gif) This doesn't not support layout properties.

2. Using the clever trick where the native driver drivers a non-native animation through an `Animated.event` (https://media.giphy.com/media/4KFGU2gkedfsxsQ62d/giphy.gif) This supports layout properties.

So how did I make it a busy app? Just added the below code on next button click handler.

```
setInterval(() => {
  for (let i = 0; i < 5e8; i++) {}
}, 1000);
```

Correct me if I am wrong, so what I think is happening here is that even though native driver is driving the non-native animation it has to still go through the bridge on every frame to update `Animated.event`.

Let me know what you think about it.

**Comment by chrfalch** [comment]
Thanks for your feedback! It is really appreciated.

What I'm trying to do with combining native/non-native animations is to run native animations like transforms and opacity using the native driver while running other animations with the non-native driven animated value. This is not a trivial task to implement so we'll see what the results will be.

**Comment by narendrashetty** [comment]
Totally makes sense. Will follow your development :)

**Comment by chrfalch** [comment]
The trick is that to be able to animate every component (also function-based stateless components which normally does not play well with animated) I'm wrapping my component and thought I could wrap in to components - one used for native animations and one for non-native animations. It's a little tricky to transfer the correct style props and build the component.

**Comment by narendrashetty** [comment]
I was also thinking, since it's not possible layout properties with native driver, how about we work on an addon which works with layout properties too. I know this is beyond the scope of this library, just thinking out loud. Don't know if it's even possible

**Comment by MrLoh** [comment]
I’m no expert on the matter but from my understanding the only performant approach to layout animations is using the [FLIP](https://aerotwist.com/blog/flip-your-animations/) technique. No matter what Plattform layout animations are just not performant because of how rendering works on native and web platforms. So animating layout properties should just be discouraged probably.

**Comment by chrfalch** [comment]
@MrLoh This library uses native animations for moving and scaling elements using a technique similar to FLIP like you are describing. The discussion here is about finding a way to open up for animating properties not supported by the native driver. There are several issues I'm working on to get this to work properly. 

First of all we have the problem of not being able to use stateless components for animating (with Animated.createAnimatedComponent). This can be solved by creating a wrapper for the stateless component and transferring shared element/transition properties.

Next we have the issue with native vs. non-native animations. I'm close to solving this by creating another set of wrappers that basically creates two outer elements, one for native animations and one for non-native animations. 

With these solutions I'm pretty confident that we can create a good-enough solution to the problems with animations, with the limitation in performance that @narendrashetty has pointed out for some of the animations, but with full native support where applicable.
