### ISSUE TITLE
Screens under FluidNavigator don't respect navigationOptions hence i can't customise header? 

### ISSUE THREAD

**Issue by zloz** [fram-x/FluidTransitions#50]
Header couldn't be customise under FluidNavigator as it doesn't respects navigationOptions, can't find any relevant example also.

` navigationOptions:({navigation,screenProps}) =>{
            return{
                headerStyle:StackNavigationHeader.headerStyle({navigation}),
                headerLeft:StackNavigationHeader.headerLeftDrawer({navigation,screenProps}),
                headerRight:StackNavigationHeader.courseHeaderRight({navigation,screenProps}),
                headerTitle:StackNavigationHeader.headerTitle({navigation})
            }    
        },`

**Comment by chrfalch** [comment]
Hi @zloz: FluidNavigator does not have a header as stated in the documentation, so this won't work. Wrap it in a parent StackNavigator to customize the header.

**Comment by zloz** [comment]
but that would restrict me to have same header(even if customised under stacknavigator) in all the screens under fluid navigator , i want to have a different header for screens under fluid navigator

**Comment by chrfalch** [comment]
Yes, but due to The complexities involved with headers this is unfortunately not feasible - you could bind the parent header to make it more dynamic. 

FluidNavigator is unfortunately not a stack navigator with header - it is a navigator for transitions that happens to use a stack router underneath.

**Comment by muhaimincs** [comment]
I have applied it just like your suggestion. But I'm having flickering issue when hide the header on second screen. 

```sh
static navigationOptions = ({navigation}) => {
    const {state: {index = 0} = {}} = navigation;
    if (index > 0) return {header: null};
    return {
      title: 'UMRAHTI',
    };
  };
```
