### ISSUE TITLE
Swiping down from second screen reveals the first

### ISSUE THREAD

**Issue by aurbina83** [fram-x/FluidTransitions#51]
```
const Navigator = FluidNavigator({
  screen1: {screen: Screen1},
  screen2: {screen: Screen2},
})
```

Just running this...navigating to screen2, if I slowly swipe down, screen2's interpolates the opacity on the drag. If I swipe all the way down, it navigates to screen1, if I continue going back up, it stays on screen2. 

It only happens when swiping from top to bottom, not bottom up or left-right/right-left.

Was there a prop to disable swiping?

**Comment by chrfalch** [comment]
Hi @aurbina83! Yes, you can use the `navigationOptions` property when setting up the navigator, see the sample code here: <https://github.com/fram-x/FluidTransitions/blob/6b1ed2d51119ea2fe147d826597863671852ce7e/Examples/src/SharedElements.js#L166>

**Comment by jordangrant** [comment]
Still an issue even with gesturesEnabled: false

**Comment by jordangrant** [comment]
Working with **defaultNavigationOptions**:

```
const SearchStack = createFluidNavigator({
  Search: { screen: SearchScreen, path: ':urlsuffix' },
  Community: { screen: CommunityScreen, path: 'c/:urlsuffix' },
},
  {
    initialRouteName: "Search",
    defaultNavigationOptions: { gesturesEnabled: false },
    navigationOptions: { }
  });
```
