### ISSUE TITLE
Feature: Add zIndex as a prop for ordering multiple shared element transitions

### ISSUE THREAD

**Issue by TimonSotiropoulos** [fram-x/FluidTransitions#53]
Hello!

Just wanted to say this library is amazing! Been able to put together some absolutely dope transitions because of it so thanks for all the hard work!

I had a problem where I was using 2 shared element transitions on the one page and wanted to customise their flow order. I am not sure exactly how they are getting laid out by your framework, but I wanted one to specifically appear above the other. Managed to get it to work with a tiny change to your code by adding zIndex as a property to the TransitionView class.

Just had to change the constructor to accept a prop or use the current zIndex method. 

    
```
// Line 59 - TransitionView.js
this.props.zIndex || zIndex++, this.props.anchor, this.props.animated
```

[Link to the code line here ->](https://github.com/fram-x/FluidTransitions/blob/1688ca97b7c9d38610d3a16e284cac3bef1cb922/src/TransitionView.js#L59)

Just thought this might be useful to others if they are having problems ordering their shared elements.

**Comment by chrfalch** [comment]
Hi @TimonSotiropoulos! Thanks for the great feedback! It is appreciated. Please feel free to add this as a Pull Request if you have the time. Creating a pull request is not hard, learn more here: <https://help.github.com/articles/creating-a-pull-request/>
