### ISSUE TITLE
RN 0.56 - element.type is not a function

### ISSUE THREAD

**Issue by AdamAtri** [fram-x/FluidTransitions#54]
[x] bug

```json
"dependencies": {
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.6.2",
    "react-navigation-fluid-transitions": "^0.2.2"
  },
```
node: v8.11.3
npm: 5.6.0
yarn: 1.7.0

**ISSUE:**
Simple Transition fails with error: `element.type is not function`. Without the Transition, navigation works fine. Adding the Transition throws the error.
``` javascript
class Screen1 extends Component {
  render() {
    return (
      <TouchableOpacity
        activeOpacity={1}
        style={s1Styles.container}
        onPress={() => this.props.navigation.navigate('screen2')}
        >
        <Transition appear="horizontal">
          <View style={s1Styles.paper}/>
        </Transition>
        <View style={s1Styles.headerContainer}>
          <Text style={s1Styles.header}>WARBUNNY</Text>
          <Text style={s1Styles.subheader}>Snuggles</Text>
        </View>
        <Image style={s1Styles.shoe} source={require('../../../assets/warbunny.png')} />
      </TouchableOpacity>
    );
  }
}
```

Error is thrown at: `ShallowRenderer.render (66:34)`.

![image](https://user-images.githubusercontent.com/6920215/42423987-c092cefe-82d1-11e8-8736-6e9174d54a38.png)

output from `console.log(element)`:
![image](https://user-images.githubusercontent.com/6920215/42423875-14044f4c-82d0-11e8-807b-6b3cb459dc25.png)

**Comment by dnazarov** [comment]
It's a problem of the react-native:0.56.0. I've downgraded my project to the react-native:0.55.4 and it's work fine.

**Comment by AdamAtri** [comment]
Holy good gravy that is awesome.
Created a new project with `react-native init --version="0.55.4" FluidProject` and it totally works.
There issue with 0.56 is still there, but this is solid.
thanks @dnazarov .

**Comment by chrfalch** [comment]
Thanks, @jvdsande - I'll test this out!

**Comment by patrick-samy** [comment]
Still present on `0.2.2` - I tried a couple of fixes but they didn't work. Any ideas?

**Comment by bilalsyed001** [comment]
Removing shouldRenderRenderElement check works for me -> https://github.com/fram-x/FluidTransitions/blob/2d41a22ecb6af4e36e642c3d88b1f503fd4f550c/src/TransitionItem.js#L68
