### ISSUE TITLE
Flicker above the FlatList

### ISSUE THREAD

**Issue by baicuhaha** [fram-x/FluidTransitions#55]
[QQ20180714-165503-HD.MP4.zip](https://github.com/fram-x/FluidTransitions/files/2194797/QQ20180714-165503-HD.MP4.zip)

The first load in the flatList's renderItem method flashes
<img width="806" alt="2018-07-14 4 58 17" src="https://user-images.githubusercontent.com/20334376/42722964-9a799256-8787-11e8-8228-5f03e07fe166.png">

**Comment by baicuhaha** [comment]
My code
<img width="806" alt="2018-07-14 4 58 17" src="https://user-images.githubusercontent.com/20334376/42722988-dfbba0d4-8787-11e8-9c5a-668196a647d8.png">

**Comment by baicuhaha** [comment]
my code 
<img width="806" alt="2018-07-14 4 58 17" src="https://user-images.githubusercontent.com/20334376/42723000-1973a7d6-8788-11e8-843b-bbd0d84ad949.png">

**Comment by baicuhaha** [comment]
my code 

 renderItem(rowData) {
        let index = rowData.index
        rowData = rowData.item;
        let img;
        if (rowData.AppearancePicUrl) {
            img = { uri: rowData.AppearancePicUrl }
        } else {
            img = require("../../../images/common/icon_default.png")
        }

        let info = this.props.navigation.state.params.info.dic
        return (
            <TouchableOpacity
                activeOpacity={1}
                style={styles.cellViewStyle}
                onPress={() => { this.props.navigation.navigate('details', { rowData: rowData, index: index, info: info }); }}
            >
                <Transition shared={`image${index}`}>
                    <ImageBackground allowFontScaling={false}
                        source={img}
                        style={styles.imageStyle}>

                        <ImageBackground allowFontScaling={false}
                            source={require('../../../images/hotel/icon_layer.png')} style={styles.layerViewStyle}>
                            <View style={styles.rateViewStyle}>
                                <Text allowFontScaling={false} style={styles.priceStyle}>￥{rowData.MinPrice} CNY</Text>
                                <RateView stars={rowData.HotelStar} />
                            </View>
                            <Text allowFontScaling={false} style={styles.nameStyle}>{rowData.HotelChnName}</Text>
                            <Text allowFontScaling={false} style={styles.distanceStyle}>距离{rowData.Distance}公里</Text>

                            <FacilityView rowData={rowData} />
                        </ImageBackground>
                    </ImageBackground>
                </Transition>
            </TouchableOpacity>
        )
    }

**Comment by chrfalch** [comment]
Hi @baicuhaha! Thanks for submitting the issue! To make it easier to investigate, please provide a minimal example using Expo that shows the flickering.

**Comment by chrfalch** [comment]
Closed due to inactivity.
