### ISSUE TITLE
componentWillUnmount - Warning: Can't call setState ...

### ISSUE THREAD

**Issue by zivchen** [fram-x/FluidTransitions#59]
Once we leave the Fluid navigator to different router we get a componentWillUnmount warning.
This is not a problem yet, and its only a warning but better to be prepared.
The entire warning log

ExceptionsManager.js:71 Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in TransitionItemsView (at FluidTransitioner.js:204)
    in RCTView (at View.js:60)
    in View (at Transitioner.js:169)
    in Transitioner (at FluidTransitioner.js:69)
    in FluidTransitioner (at createFluidNavigator.js:35)
    in FluidNavigationView (at createNavigator.js:57)
    in Navigator (at createNavigationContainer.js:368)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:516)
    in RCTView (at View.js:60)
    in View (at createAnimatedComponent.js:154)
    in AnimatedComponent (at StackViewCard.js:12)
    in Card (at createPointerEventsContainer.js:28)
    in Container (at StackViewLayout.js:554)

**Comment by chrfalch** [comment]
Hi @zivchen! Thanks for submitting this issue. Would it be possible to create a simple reproduction on Expo so that we can investigate?

**Comment by chrfalch** [comment]
Closed due to inactivity
