### ISSUE TITLE
Can you create an Example with nested navigator (StackNavigator, TabNavigator, DrawerNavigator)?

### ISSUE THREAD

**Issue by ducpt2** [fram-x/FluidTransitions#6]
Please, Can you create an Example with nested navigator (StackNavigator, TabNavigator, DrawerNavigator)?

I'm very appreciate your huge efforts. Thanks.

**Comment by chrfalch** [comment]
The Example has a nesten setup. If you’re unable to integrate with other navigators please provide a snack as an example. Also verify that it works with a regular StackNavigator before creating the issue. Thanks!

**Comment by ducpt2** [comment]
this is last of my effort to trying contributed to this lib.
https://snack.expo.io/ByfA7bqjG
I'm not work with snack before, so i push my code on snack. This code work simple with react-navigation, but when using FluidNavigator it not work like i expect.
Can you try test with your own when you close? Do you want to make this library better?

**Comment by chrfalch** [comment]
You're probably using the library a bit "upside down" - it is built for building transitions between screens - not between nested navigators. You will not see any results the way you use it - a FluidNavigator does not know how to transition between sub navigators. Use FluidNavigator for the screens and build transitions in these screens - that should probably work.

**Comment by ducpt2** [comment]
" it is built for building transitions between screens" - That is one of my thought. Very thanks your suggestion. I will try to find out how to do this way. <3

**Comment by plus-** [comment]
> You're probably using the library a bit "upside down" - it is built for building transitions between screens - not between nested navigators. You will not see any results the way you use it - a FluidNavigator does not know how to transition between sub navigators. Use FluidNavigator for the screens and build transitions in these screens - that should probably work.

What would be the solution to transition between a screen and a modal (as defined in https://reactnavigation.org/docs/en/modal.html)

for example between the ModalScreen and the DetailsScreen in this picture:
https://reactnavigation.org/docs/assets/modal/tree.png

modal must be defined at the top most stack, but I don't want to create a fluid navigator on the top most stack as I only define transition between the modal and some of the screen.

This is related to #178
