### ISSUE TITLE
Transition speed decreases with multiple "shared" elements

### ISSUE THREAD

**Issue by Ketn** [fram-x/FluidTransitions#64]
So I'm using shared element transition to achieve something like the App Store in iOS: https://vimeo.com/272028619

So as the animation (and title) suggests, I have 3-4 shared elements from the **ThumbnailScreen** to the **DetailsScreen** and the transition takes about **2.5 seconds**. When I only have one element, the transition takes about **0.9-1.1 seconds**, with 2 elements around **1.6-1.9 seconds** and so on.

I assume this is due to the time it takes to calculate the position and other props of the Destination screen's shared elements... 

Is this something expected or something that shouldn't happen?
 Is there any way to improve the performance if I HAVE TO use 4 shared elements?

[Snack Expo Demo](https://snack.expo.io/B1PA9XD4Q)

Thanks!

**Comment by chrfalch** [comment]
Hi @Ketn! Thanks for submitting the issue. Would it be possible to create a minimal reproduction on Expo to be able to investigate this?

**Comment by Ketn** [comment]
@chrfalch I have added an expo demo, however, I don't see the problem existing in this isolated example. But, this problem specifically happens for FluidNavigator as I tried StackNavigator and it didn't give any such delays. I've debugged my app code for hours, and the problem occurs only in FluidNavigation with a significant increase in delays everytime I increase the number of shared elements.

Is there any factor, that I missed, that causes increased loading times / delays specifically in FluidNavigation?

**Comment by chrfalch** [comment]
@Ketn Hi, I tried your example, and as you say it doesn't exhibit the problem you are describing. 

Could it be that you are doing some calculations and processing or downloading in your component's code that can slow down the transition? Unfortunately the Fluid Transitions library performs a few extra render rounds to be able to calculate sizes and positions - try inserting some `console.log` statements in your code if you do any downloads or time consuming processing.

**Comment by chrfalch** [comment]
Closed due to inactivity.
