### ISSUE TITLE
White background when open from StackNavigatior

### ISSUE THREAD

**Issue by jonathanmauer** [fram-x/FluidTransitions#7]
When i open a FluidNavigator from a StackNavigator i get a white background when its loading screens. Can i remove this delay?

**Comment by ZeeStorm** [comment]
https://github.com/fram-x/FluidTransitions/blob/develop/src/FluidTransitioner.js#L247

I wonder if it's caused by this white background? Doesn't seem override-able in its current state.

**Comment by bkdev98** [comment]
I got the same issue here. Also, the header bar from StackNavigator does not display.

**Comment by chrfalch** [comment]
This seems like a shortcoming related to the fact that all new screens are faded in. Even after removing the referenced line from (@ZeeStorm) it won't start of with the same color as the first screen. I'll look into this and see if I can find an easy fix.

**Comment by saurabh874** [comment]
@chrfalch  any solution to this?
i am facing same issue when I open from StackNavigator.
