### ISSUE TITLE
How to define gesture direction in component?

### ISSUE THREAD

**Issue by FelipeBohnertPaetzold** [fram-x/FluidTransitions#71]
I have a FluidNavigator where I need to set two different directions in the gesture to go back to the page. Is it possible to define the desired direction dynamically?

**Comment by chrfalch** [comment]
Hi @FelipeBohnertPaetzold!

The `Onboarding.js` example has a setup that changes the direction to horizontal:

```js

const Navigator = FluidNavigator({
  screen1: { screen: Screen1 },
  screen2: { screen: Screen2 },
  screen3: { screen: Screen3 },
}, {
  mode: 'card',
  navigationOptions: {
    gesturesEnabled: true,
  },
});
´´´
