### ISSUE TITLE
First transition does not behave as expect, subsequent ones do

### ISSUE THREAD

**Issue by patrick-samy** [fram-x/FluidTransitions#73]
Hey folks,

I observe this behavior consistently after starting the app, even in release configuration.

The first transition is either using the default fade in, or moving the shared elements in the opposite direction, which looks like a weird glitch for the end user.

All subsequent transitions are behaving as expected.

I've been reading multiple issues that could be associated to try and fix things, without success. I'm using these versions.
```
    "react-native": "^0.56.0-rc.5",
    "react-navigation": "^2.6.2",
    "react-navigation-fluid-transitions": "^0.2.2",
```

If this isn't a known issue, I'll try to build a minimum code to reproduce this.

**Comment by chrfalch** [comment]
Hi @patrick-samy, Thanks for submitting an issue. Please provide a working, simple example using http://snack.expo.io/ that displays this behavior so that I can investigate it.

**Comment by patrick-samy** [comment]
Hi @chrfalch, couldn't reproduce it with this: https://snack.expo.io/SkWnkZwLQ

However, I seem to have been able to fix the issue. I think the way Relay was re-rendering my component after the GraphQL request caused some issues.

I refactored the code and it now works smoothly. Thanks again :)
