### ISSUE TITLE
Navigation to any screen, different from starting one outside of FluidNavigator fails

### ISSUE THREAD

**Issue by todorone** [fram-x/FluidTransitions#77]
When we navigate to the 1st screen of FluidNavigator, it works.

If we try to navigate directly to the 2nd screen of FluidNavigator, it doesn't appear.

Repro: https://snack.expo.io/HJMqtQOUm

**Comment by jpapillon** [comment]
+1

**Comment by jpapillon** [comment]
Workaround: create another route for the routes you want direct access to. For example, if you've got Screen A and Screen B, you can create the transition using another route name:
`const Navigator = FluidNavigator({
  screenA: { screen: ScreenA },
  screenBShared: { screen: ScreenB },
})`

In your main router, you simply create a `screenB` route name that points to `ScreenB` as well. So, if you want to access ScreenB from ScreenA (with the shared animations), you would navigate to `screenBShared`. If you want to go straight to `ScreenB`, you can simply navigate to `screenB`.

This issued should probably be fixed so we can access without problems to any of the screens in the FluidNavigator, but this can be a temporary workaround...
