### ISSUE TITLE
Components that are children of Transition component are not being registered by `ref` property

### ISSUE THREAD

**Issue by todorone** [fram-x/FluidTransitions#78]
We may need to register children of `Transition` component by `ref`, but it doesn't work.

Repro: https://snack.expo.io/BylDamOLQ

- when tapped on "Check reference value" => Reference value is `true`
- if we remove `Transition`, covering `TextInput`, when tapped on "Check reference value" => Reference value is `false`

Pls, let me know if repro is too awkward to grasp... :)

**Comment by chrfalch** [comment]
Thanks again, @todorone :-) Will take a look and see!

**Comment by chrfalch** [comment]
@todorone, would suggest that you wrap the `TextInput` in a `View` - that should do it.

**Comment by todorone** [comment]
@chrfalch Thanks for the hint. For now, I've made a little patch to package adding `innerRef` prop to `Transition` component. I can make PR, but don't think it's the best way to solve this bug...

**Comment by chrfalch** [comment]
If you have a suggestion for a solution I'd be happy to test it out. A PR is much welcome @todorone

**Comment by chrfalch** [comment]
Closed in PR #109
