### ISSUE TITLE
Flickering when first loading navigator

### ISSUE THREAD

**Issue by AdamPD** [fram-x/FluidTransitions#80]
When first loading the navigator, there appears to be a flicker moment where the navigator shows a blank view.  This is using 0.2.3.

In our fork, this commit solved it:

https://github.com/pharmadata/FluidTransitions/commit/60cb24790272e4ac1d020ea3cdc403e1fb4e5481

Not sure exactly what's going on or why that's there.

**Comment by chrfalch** [comment]
Hi @AdamPD, thanks for submitting the issue and suggesting a fix.

From the diff you sent me it seems like the only thing changed (except for some whitespace changes) was line 56:

```js
this._transitionProgress.setValue(-1);
```

When removing this line you won't get the initial transition into the first screen, so this fixes the issue but introduces another one. 

Is this correct?

**Comment by chrfalch** [comment]
I'ved tried another thing that might work.

In the file `TransitionConstants.js`, change the value for the `TRANSITION_PROGRESS_START` constant to `0.000000001` and see if it helps. (you might need to revert the change you made).

**Comment by chrfalch** [comment]
Closing this one due to inactivity.

**Comment by AdamPD** [comment]
@chrfalch - it didn't seem to affect the initial transition at all.

**Comment by chrfalch** [comment]
See PR #79 and #93 - they are now part of release 0.2.6 which contains a few optimizations to avoid flickering. Btw, did you test to see if there is a difference on the Simulator and the real device?

**Comment by nwaughachukwuma** [comment]
Hi @chrfalch I still experience this flickering in my emulator. And when going from stacknavigator to fluid navigator. Is there a permanent fix now?
