### ISSUE TITLE
Gradients or images inside of <Transition> component being clipped or not rendering on android device

### ISSUE THREAD

**Issue by Zazzzles** [fram-x/FluidTransitions#86]
I have only been having this issue on a physical android device. Everything works perfectly on emulated iOS.

I am currently using a Transition component to animate an image like this:

```
<Transition appear={'scale'} anchor='topblock'>
          <View style={{
            width: 300, 
            height: 300,   
            left: width- 100,  
            transform: [{rotate: "80deg"}],
            borderRadius: 15,
            top: height- 220,
            position: 'absolute', 
            overflow: 'hidden',
            }}>
            <Image
              source={Block}
            />
             
            </View>
        </Transition>
```

And when testing on android device, sometimes the image either clips or does not show up at all only when wrapped with `<Transition>`. If not wrapped with `<Transition>` the image displays perfectly with correct styling as provided by the parent view.

The same happens on android device when using Expo's `<LinearGradient>` : 

```
 <Transition appear={'scale'} anchor='topblock'>
            <LinearGradient
                  colors={[colors.primary, colors.secondary]}
                  style={{
                      height: 300, 
                      width: 300, 
                      borderRadius: 15,
                      zIndex:-10,
                      left: width- 100,  
                      top: height- 220,
                      position: 'absolute', 
                      transform: [{rotate: "80deg"}]
                  }}
                  start={[1, 0]}
                  end={[0,1]}
              >
          </LinearGradient>
        </Transition>

```

It works perfectly cross platform when not using an image or gradient like this : 

```
<Transition appear={'scale'} anchor='topblock'>
          <View style={{
            width: 300, 
            height: 300,   
            left: width- 100,  
            transform: [{rotate: "80deg"}],
            borderRadius: 15,
            top: height- 220,
            position: 'absolute', 
            backgroundColor: colors.tertiary
            }}>
             
            </View>
        </Transition>
```

I hope this is something I am doing wrong on my side but I have been playing around with this for quite some time.

**Comment by ZiedBeta** [comment]
Hi,

I have seen that you closed the issue. Did you find a way to solve it ?
I am having the same behavior: Using expo, and wrapping a LinearGradient with a <Transition/>

I am testing on a iOS (iPhone X)

**Comment by ZiedBeta** [comment]
I have solved the issue on my end.
The wrapper container was not having the correct size.

**Comment by Zazzzles** [comment]
@ZiedBeta Yes solved it on my side by tweaking the wrapper container as well.
