### ISSUE TITLE
Header options get's ignored (no header)

### ISSUE THREAD

**Issue by glenngijsberts** [fram-x/FluidTransitions#88]
I am trying out this dependency and I was replacing the `createStackNavigator`  with `FluidNavigator`. I have now this problem that my header get's removed, why is that?

```javascript
// The one where the header is removed
const HomeStack = FluidNavigator(
    {
        Home: { screen: HomeScreen },
        Evenementen: { screen: EventsScreen },
    },
    {
        ...stackNavigatorOptions,
    }
);

//The one where the header is stil lthere
const ContactsStack = createStackNavigator(
    {
        Contacts: { screen: ContactsScreen },
    },
    {
        ...stackNavigatorOptions
    }
);

// Headeroptions
const stackNavigatorOptions = {
    headerMode: 'screen',
    navigationOptions: {
        gesturesEnabled: true,
    },
};

export default stackNavigatorOptions;
```

I am using 

    "react-navigation": "^2.12.1",
    "react-navigation-fluid-transitions": "^0.2.5"

**Comment by chrfalch** [comment]
Hi @glenngijsberts! the Fluid Navigator does not have a header - this is documented in the readme file as one of the few differences between the `StackNavigator` and the `FluidNavigator`.

**Comment by matheushf** [comment]
So, if I use this for animations, I will lose all my headers?
