### ISSUE TITLE
Weird text alignment while transition is happening

### ISSUE THREAD

**Issue by tushgup** [fram-x/FluidTransitions#91]
Hi! I'm new to React Native so there's a chance this is a silly doubt... 

I'm navigating from `Screen1` using `TouchableHighlight` and its `onPress` to `Screen2` using `react-navigation`.

I applied the `share="searchBar"` attribute to components which need to share the transition, and wrapped them under the `<Transition>` tag. 

But the transition looks something like this:

![fluidtransitionbug](https://user-images.githubusercontent.com/5716459/44934298-f5288b80-ad89-11e8-978e-ddb75c69a440.gif)

Code: 
Screen 1:
```
<Transition shared="searchBar">
            <View style={{ justifyContent: 'center', alignItems: 'center'}}> 
              <TouchableOpacity style={styles.searchBar} 
              onPress={ () => this.props.navigation.navigate('SearchInput')}>
                  <Text style={styles.searchBarText}>Search for products</Text>
              </TouchableOpacity>
            </View>
        </Transition>
```
Screen 2: 
```
<Transition shared="searchBar">
    <SearchBar 
     placeholder="Search for product..."
     // Bunch of other props for this component
     />
</Transition>
```

**The issue**: As evident, 'Search for products' from the first screen behaves weirdly while transitioning to the second screen. How can I make this behaviour smoother? Is it possible to have a behaviour where that same text is being transitioned to the next screen inside the `SearchHeader` component? 

Any advice is appreciated! Still figuring React Native out. Thanks in advance!

**Comment by mzgnr** [comment]
I think header is causing that. Why not put a transparent header ?

**Comment by chrfalch** [comment]
Hi @tushgup! Thanks for submitting an issue.

The reason for your weird transition is that you are trying to transition between two very different components - a `SearchBar` and a custom component you've created. The transitioner in Fluid Transitions doesn't have any knowledge about this and tries to do its best - which is to move, scale and transform the first component into the second.

The correct way to do this would be to create two similar components with the same alignment and padding and then transform them. You can also build custom transitions - look at the sample code in the `AnimatedProperty.js` file for some hints.
