### ISSUE TITLE
Component within Transition mounts multiple times

### ISSUE THREAD

**Issue by danwoodbury** [fram-x/FluidTransitions#93]
Hi, any component that is within a `<Transition />` component is being mounted more than once. As soon as i remove the `Transition` component it is fine. This makes the user experience terrible if you want to do something like autofocus a textfield where the keyboard just keeps flickering in and out

**Comment by chrfalch** [comment]
Hi @danwoodbury, thanks for submitting an issue. Closing this with PR #95 :-)

**Comment by WillyRamirez** [comment]
@chrfalch  I see that this PR has been merged, but I am still experiencing this behaviour. 
When I add "inline" as a prop the rerendering stops, but then the transition animation is no longer taking place, and the components just appear on the screen. 

Any thoughts?
