### ISSUE TITLE
Support different aspect ratios for shared element transitions

### ISSUE THREAD

**Issue by israelidanny** [fram-x/FluidTransitions#97]
While transitioning between two images, if they are of different aspect ratios, the image gets distorted and stretched in a very ugly way.

Is there any way to specify something like `resizeMode="cover"` for the transition effect?

**Comment by chrfalch** [comment]
@israelidanny Thanks for submitting your issue. Unfortunately there is no way that Fluid Transitions knows how to transition between two elements that appear different on screen. However, there is a way to pass the progress into the transitioned component to make it easier to perform custom transitions. You can see an example of this is the `AnimatedProperty.js` file in the Examples folder.

**Comment by israelidanny** [comment]
@chrfalch well, I'm not sure about the inner workings, so this question might be silly, but since `<Image />` has a built in `resizeMode`, wouldn't it be possible to simply pass `resizeMode="cover"` and let it automatically resize correctly?

**Comment by chrfalch** [comment]
I don't believe the `Image` component has any built-in-knowledge about animating its resize mode - but it should be possible to build such a component.

**Comment by israelidanny** [comment]
@chrfalch we wouldn't need to animate `resizeMode` at all. Once it is set to `cover`, it automatically adjusts the layout of the image upon resizing. The trick is to just set it before starting the animation.

**Comment by chrfalch** [comment]
The trick is to tell the image that it should adjust the layout using an animated value, and that might be a little bit tricky.

**Comment by israelidanny** [comment]
@chrfalch I'm a little confused. Where does animation come into play? `resizeMode` is a static value.
I'm not at all suggesting to change it "mid flight", but rather to just specify it once.

If I understand correctly, the router works by creating an intermediate image that matches all the properties of the original one, correct? All it would have to do is assume the same `resizeMode` at creation time as the original image.

**Comment by chrfalch** [comment]
Fluid Transitions takes the element defined in the from-screen and creates an animation based on the differences in styles between it and the element in the to-screen. It does not know anything about the `resizeMode` of the image component so this is not animated. You can change it in the two elements, but it would result in a "jump" when the transition is done. You probably need to create a custom interpolation for the image based on the transition animated value.

**Comment by israelidanny** [comment]
@chrfalch Either we have a little bit of a miscommunication or I'm misunderstanding something. Why do you say `to animate resizeMode`. It does *not* need to be animated :) Just inherited!

`resizeMode` is a 100% static property. It just tells the layout engine how to size the image inside the `<Image />` component.

**Comment by chrfalch** [comment]
A solution in Fluid Transitions would probably be to build some knowledge about size for components - so that if the to/from shares the same aspect ratio, transform/scale can be used, otherwise size would be used.

**Comment by israelidanny** [comment]
@chrfalch How would I approach trying to animate size instead of transform (even though it is slower?). For this situation it's a requirement, I guess.

Would it require a pull request here? 

I'm open to directions.

**Comment by chrfalch** [comment]
A PR would be perfect, give me a few minutes and I'll see what I can do here first :-)

**Comment by chrfalch** [comment]
It took a bit of work, but I have successfully created something that I believe could solve the aspect ratio issue - not only for images. Take a look at the branch #98 and see if it might be what you're looking for!

**Comment by israelidanny** [comment]
@chrfalch Any special usage instructions or differences? Checking it...

**Comment by chrfalch** [comment]
Nope, just test with shared elements with different aspect ratios ;-)

**Comment by chrfalch** [comment]
Nice!!

**Comment by chrfalch** [comment]
Closed by #98

**Comment by AkilLis** [comment]
Great!. @chrfalch when changes are published into master ?

**Comment by chrfalch** [comment]
Hopefully during the weekend, @AkilLis .
