### ISSUE TITLE
Error when using shared Animated.Image wrapped in Transition

### ISSUE THREAD

**Issue by israelidanny** [fram-x/FluidTransitions#99]
I changed my `Image` to `Animated.Image` for the purpose of fading in after an onLoad, and FluidTransitions doesn't seem to like it too much. This is the error I'm getting. If I revert back to `Image`, everything works.

![screen shot 2018-09-19 at 16 22 47](https://user-images.githubusercontent.com/1970424/45756132-c6832f80-bc28-11e8-9d24-4b7dfaa8d143.png)

**Comment by israelidanny** [comment]
Also, wrapping an `Animated.View` breaks any animation it might have.

**Comment by chrfalch** [comment]
You shouldn't need to wrap to fade - this is built-into Fluid Navigator.

**Comment by chrfalch** [comment]
But I see the issue. Will look into it as well ;-)

**Comment by israelidanny** [comment]
@chrfalch my use case was more like a `FlatList` with lots of image backgrounds. To give them a nice loading effect, I fade them in. This has nothing to do with transitions.

**Comment by chrfalch** [comment]
Closed by #101
